// src/lib/negara.ts
// [pendataan-negara-v1] Daftar negara untuk form pendataan siswa.
//
// Sebelum ini form pendataan memaksa semua siswa memilih salah satu dari 38
// provinsi Indonesia. Siswa yang tinggal di luar negeri (kelas online, jadi
// jumlahnya tidak sedikit) jadi buntu di langkah pertama dan harus bertanya ke
// CS — persis yang terjadi pada siswa Kelas Private German 07 Sep 2026.
//
// Indonesia sengaja ditaruh paling atas: mayoritas siswa memilihnya, dan
// dropdown-nya punya kolom cari jadi negara lain tetap gampang ditemukan.

export const NEGARA_ID = "Indonesia";

export const NEGARA: string[] = [
  NEGARA_ID,
  "Afghanistan",
  "Afrika Selatan",
  "Albania",
  "Aljazair",
  "Amerika Serikat",
  "Andorra",
  "Angola",
  "Antigua dan Barbuda",
  "Arab Saudi",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahama",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belanda",
  "Belarus",
  "Belgia",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia dan Herzegovina",
  "Botswana",
  "Brasil",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Ceko",
  "Chad",
  "Chili",
  "Denmark",
  "Djibouti",
  "Dominika",
  "Ekuador",
  "El Salvador",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Filipina",
  "Finlandia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Ghana",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guinea Khatulistiwa",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hongaria",
  "India",
  "Inggris (Britania Raya)",
  "Irak",
  "Iran",
  "Irlandia",
  "Islandia",
  "Israel",
  "Italia",
  "Jamaika",
  "Jepang",
  "Jerman",
  "Kamboja",
  "Kamerun",
  "Kanada",
  "Kazakhstan",
  "Kenya",
  "Kirgizstan",
  "Kiribati",
  "Kolombia",
  "Komoro",
  "Kongo (Brazzaville)",
  "Kongo (Kinshasa)",
  "Korea Selatan",
  "Korea Utara",
  "Kosta Rika",
  "Kroasia",
  "Kuba",
  "Kuwait",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lituania",
  "Luksemburg",
  "Madagaskar",
  "Makau",
  "Makedonia Utara",
  "Maladewa",
  "Malawi",
  "Malaysia",
  "Mali",
  "Malta",
  "Maroko",
  "Mauritania",
  "Mauritius",
  "Meksiko",
  "Mesir",
  "Mikronesia",
  "Moldova",
  "Monako",
  "Mongolia",
  "Montenegro",
  "Mozambik",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Niger",
  "Nigeria",
  "Nikaragua",
  "Norwegia",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestina",
  "Panama",
  "Pantai Gading",
  "Papua Nugini",
  "Paraguay",
  "Perancis",
  "Peru",
  "Polandia",
  "Portugal",
  "Qatar",
  "Republik Afrika Tengah",
  "Republik Dominika",
  "Rumania",
  "Rusia",
  "Rwanda",
  "Saint Kitts dan Nevis",
  "Saint Lucia",
  "Saint Vincent dan Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome dan Principe",
  "Selandia Baru",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapura",
  "Siprus",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "Spanyol",
  "Sri Lanka",
  "Sudan",
  "Sudan Selatan",
  "Suriah",
  "Suriname",
  "Swedia",
  "Swiss",
  "Taiwan",
  "Tajikistan",
  "Tanjung Verde",
  "Tanzania",
  "Thailand",
  "Timor Leste",
  "Togo",
  "Tonga",
  "Trinidad dan Tobago",
  "Tunisia",
  "Turki",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraina",
  "Uni Emirat Arab",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatikan",
  "Venezuela",
  "Vietnam",
  "Yaman",
  "Yordania",
  "Yunani",
  "Zambia",
  "Zimbabwe",
];

/** Baris lama (sebelum kolom `country` ada) tidak punya negara sama sekali —
 *  waktu itu formulirnya cuma bisa Indonesia, jadi kosong = Indonesia. */
export function isIndonesia(negara: string | null | undefined): boolean {
  return !negara || negara.trim().toLowerCase() === NEGARA_ID.toLowerCase();
}
