"use client";

/* [ui-lang-switcher-v1] Bahasa antarmuka dashboard siswa (ID ⇄ EN).
   ────────────────────────────────────────────────────────────────
   Sengaja TANPA provider/context: pemilihnya duduk di top bar `/akun`, tapi
   yang harus ikut berganti tersebar sampai ke StudentShell, bottom nav mobile,
   dan komponen tab (Perpustakaan dll). Membungkus semuanya dengan Provider
   berarti menyentuh tiap halaman ber-shell; store modul + `useSyncExternalStore`
   memberi hasil yang sama tanpa satu pun pohon komponen diubah.

   Kunci terjemahan = KALIMAT INDONESIA-nya. Jadi teks yang belum diterjemahkan
   tetap tampil apa adanya (bukan "missing.key"), dan menambah terjemahan cukup
   menambah satu baris di kamus EN di bawah — tak perlu menyentuh komponennya. */

import { useCallback, useEffect, useSyncExternalStore } from "react";

export type UiLang = "id" | "en";

export const UI_LANG_KEY = "linguo_ui_lang";

let current: UiLang = "id";
let hydrated = false;
const subs = new Set<() => void>();

function emit() {
  for (const fn of subs) fn();
}

/** Baca pilihan tersimpan. Dipanggil SESUDAH hidrasi, bukan saat render pertama:
    render server selalu "id", jadi membacanya lebih awal = hydration mismatch. */
function hydrate() {
  if (hydrated || typeof window === "undefined") return;
  hydrated = true;
  try {
    const saved = localStorage.getItem(UI_LANG_KEY);
    if (saved === "en" || saved === "id") {
      if (saved !== current) {
        current = saved;
        document.documentElement.lang = saved;
        emit();
      }
    }
  } catch {
    /* localStorage diblokir → tetap pakai bawaan */
  }
}

export function getUiLang(): UiLang {
  return current;
}

export function setUiLang(next: UiLang) {
  if (next === current) return;
  current = next;
  hydrated = true;
  try {
    localStorage.setItem(UI_LANG_KEY, next);
    document.documentElement.lang = next;
  } catch {
    /* abaikan */
  }
  emit();
}

function subscribe(fn: () => void) {
  subs.add(fn);
  return () => {
    subs.delete(fn);
  };
}

const serverSnapshot = () => "id" as UiLang;

/** Bahasa aktif + ikut re-render saat diganti dari mana pun. */
export function useUiLang(): UiLang {
  const lang = useSyncExternalStore(subscribe, getUiLang, serverSnapshot);
  useEffect(hydrate, []);
  return lang;
}

/** `const t = useT()` lalu `t("Beranda")`. */
export function useT(): (s: string) => string {
  const lang = useUiLang();
  return useCallback((s: string) => (lang === "en" ? EN[s] ?? s : s), [lang]);
}

/** Terjemahan sekali pakai di luar komponen (mis. label yang dirakit di helper). */
export function tr(s: string, lang: UiLang = current): string {
  return lang === "en" ? EN[s] ?? s : s;
}

/* ── Kamus Inggris ────────────────────────────────────────────────────────── */
const EN: Record<string, string> = {
  /* Navigasi sidebar & bottom nav */
  "Beranda": "Home",
  "Jadwal": "Schedule",
  "Grup Kelas": "Class Group",
  "Perpustakaan": "Library",
  "Sertifikat": "Certificates",
  "Kelas & Materi": "Classes & Materials",
  "Lingbook": "Lingbook",
  "Simulasi Tes": "Test Simulation",
  "Watch & Learn": "Watch & Learn",
  "Kosakata Saya": "My Vocabulary",
  "Pengaturan": "Settings",
  "Aktivitas": "Activity",
  "Belajar": "Learn",
  "Akun": "Account",
  "Materi": "Materials",
  "Profil": "Profile",

  /* Aksi umum di shell */
  "Lapor Bug": "Report a Bug",
  "Keluar": "Log out",
  "Mode terang": "Light mode",
  "Mode gelap": "Dark mode",
  "Buka menu": "Open menu",
  "Tutup menu": "Close menu",
  "Menu utama": "Main menu",
  "Menu utama mobile": "Mobile main menu",
  "Siswa": "Student",
  "Siswa Linguo": "Linguo Student",
  "Bahasa antarmuka": "Interface language",
  "Bahasa Indonesia": "Indonesian",
  "Bahasa Inggris": "English",
  "Buka": "Open",
  "Navigasi utama": "Main navigation",
  "Watch": "Watch",
  "di tab baru": "in a new tab",

  /* Top bar /akun */
  "Cari kelas, pengajar, atau bahasa…": "Search classes, teachers, or languages…",
  "Cari di dashboard": "Search the dashboard",
  "Kosongkan pencarian": "Clear search",
  "Buka panel profil": "Open profile panel",
  "Tutup panel profil": "Close profile panel",

  /* Perpustakaan */
  "Perpustakaan Saya": "My Library",
  "Lingbook & E-Learning yang sudah kamu beli · buka kapan saja":
    "Lingbook & E-Learning you've purchased · open them anytime",
  "Perpustakaan masih kosong": "Your library is still empty",
  "Kamu belum punya Lingbook atau E-Learning. Jelajahi toko untuk mulai belajar mandiri kapan saja.":
    "You don't have any Lingbook or E-Learning yet. Browse the store to start learning on your own, anytime.",
  "Jelajahi Toko Digital": "Browse the Digital Store",
  "Cari produk…": "Search products…",
  "Semua": "All",
  "E-Learning": "E-Learning",
  /* [lingbook-nama-ebook-v1] Rak e-book di Perpustakaan sekarang bernama
     "Lingbook" — nama merek, sama di ID & EN. Baris "E-Book" ditahan karena
     enum program di DB masih memakainya (riwayat tagihan, sertifikat). */
  "E-Book": "E-Book",
  "produk": "products",
  "sedang berjalan": "in progress",
  "sertifikat": "certificates",
  "Tampilan grid": "Grid view",
  "Tampilan daftar": "List view",
  "Dashboard": "Dashboard",

  /* Grup Kelas */
  "Ngobrol dengan pengajarmu di grup WhatsApp kelas — tanpa keluar dari dashboard.":
    "Chat with your teacher in the class WhatsApp group — without leaving the dashboard.",
  "Cari grup kelas…": "Search class groups…",
  "Pilih grup kelas di sebelah kiri untuk membuka percakapan.":
    "Pick a class group on the left to open the conversation.",
  "Tulis pesan ke grup kelas…": "Write a message to the class group…",
  "Kirim": "Send",
  "Muat ulang": "Reload",

  /* Pengaturan */
  "Bahasa Antarmuka": "Interface Language",
  "Kelola akun & preferensimu": "Manage your account & preferences",
  "Preferensi Belajar": "Learning Preferences",
  "Pengingat Belajar": "Study Reminders",
  "Pemutaran Rekaman": "Recording Playback",
  "Nama, foto, bio": "Name, photo, bio",
  "Akun & Keamanan": "Account & Security",
  "Email, kata sandi": "Email, password",
  "Notifikasi": "Notifications",
  "Email, WhatsApp, push": "Email, WhatsApp, push",
  "Bahasa, pengingat": "Language, reminders",
  "Tagihan & Paket": "Billing & Packages",
  "Langganan, cicilan": "Subscriptions, installments",
  "Simpan Perubahan": "Save Changes",

  /* ── Tanggal & waktu (kalender Jadwal, kartu sesi, rapor) ───────────────── */
  "Januari": "January", "Februari": "February", "Maret": "March", "April": "April",
  "Mei": "May", "Juni": "June", "Juli": "July", "Agustus": "August",
  "September": "September", "Oktober": "October", "November": "November", "Desember": "December",
  "Jan": "Jan", "Feb": "Feb", "Mar": "Mar", "Apr": "Apr", "Jun": "Jun", "Jul": "Jul",
  "Agu": "Aug", "Sep": "Sep", "Okt": "Oct", "Nov": "Nov", "Des": "Dec",
  "Senin": "Monday", "Selasa": "Tuesday", "Rabu": "Wednesday", "Kamis": "Thursday",
  "Jumat": "Friday", "Sabtu": "Saturday", "Minggu": "Sunday",
  "Sen": "MON", "Sel": "TUE", "Rab": "WED", "Kam": "THU", "Jum": "FRI", "Sab": "SAT", "Min": "SUN",
  "Hari": "Day", "Bulan": "Month",
  "Hari ini": "Today", "Hari Ini": "Today", "Berikutnya": "Next", "Sebelumnya": "Previous",
  "besok": "tomorrow", "menit": "minutes", "mnt": "min", "jam": "hours",
  "menit lagi": "min left", "jam lagi": "hr left", "hari lagi": "days left",
  "sedang berlangsung": "in progress", "Sedang berlangsung": "In progress", "Live": "Live",
  "selesai": "ends", "Setiap": "Every",

  /* ── Sapaan beranda ─────────────────────────────────────────────────────── */
  "Selamat pagi": "Good morning",
  "Selamat siang": "Good afternoon",
  "Selamat sore": "Good evening",
  "Selamat malam": "Good evening",
  "yuk belajar bahasa hari ini!": "let's learn a language today!",
  "Ga ada yang cocok sama": "Nothing matches",

  /* ── Kartu kelas & seksi beranda ────────────────────────────────────────── */
  "Perlu Perhatian": "Needs Attention",
  "Belum Bayar": "Unpaid",
  "Bayar": "Pay",
  "Lihat detail": "View details",
  "Batalkan pendaftaran": "Cancel enrollment",
  "Kelas Live": "Live Classes",
  "Belajar Mandiri": "Self-Study",
  "Aktif": "Active",
  "Riwayat": "History",
  "Tambah": "Add",
  "Tambah Kelas": "Add a Class",
  "Daftar Kelas": "Enroll in a Class",
  "Selesai": "Completed",
  "Sesi": "Session",
  "sesi": "sessions",
  "kelas": "classes",
  "Lanjut": "Continue",
  "Ulangi": "Repeat",
  "Private": "Private",
  "Semi Private": "Semi Private",
  "Reguler": "Regular",
  "Kids": "Kids",
  "Semi Private Kids": "Semi Private Kids",
  "Test Prep": "Test Prep",
  "Kelas Private": "Private Class",
  "Kelas Semi Private": "Semi Private Class",
  "Kelas Reguler": "Regular Class",
  "Kelas Kids": "Kids Class",
  "Kelas Semi Private Kids": "Semi Private Kids Class",
  "English Test Preparation (IELTS/TOEFL)": "English Test Preparation (IELTS/TOEFL)",
  "Satu pengajar khusus buat kamu, jadwal fleksibel.": "One dedicated teacher just for you, flexible schedule.",
  "Grup kecil, jadwal disepakati bareng anggota grup.": "Small group, schedule agreed with the other members.",
  "Kelas berkelompok per batch dengan jadwal tetap.": "Group class per batch with a fixed schedule.",
  "Kelas anak dengan materi & pendekatan khusus.": "Kids class with dedicated materials & approach.",
  "Grup kecil khusus anak.": "Small group just for kids.",
  "Persiapan tes IELTS/TOEFL bareng pengajar spesialis.": "IELTS/TOEFL test prep with specialist teachers.",
  "Belum ada riwayat kelas": "No class history yet",
  "Kelas yang sudah selesai akan muncul di sini.": "Classes you've finished will show up here.",
  "Belum ada kelas live aktif": "No active live class yet",
  "Mulai belajar bahasa baru sekarang!": "Start learning a new language now!",
  "Belum ada paket belajar mandiri": "No self-study package yet",
  "Belajar sendiri kapan saja lewat paket E-Learning.": "Learn on your own anytime with an E-Learning package.",
  "Semua Silabus (60+ Bahasa)": "All Syllabuses (60+ Languages)",
  "Blog & Tips Belajar": "Blog & Learning Tips",

  /* ── Ringkasan Belajar (beranda) ────────────────────────────────────────── */
  "Ringkasan Belajar": "Learning Summary",
  "PR menunggu": "homework pending",
  "Tutup": "Close",
  "Lihat": "View",
  "Jam belajar minggu ini": "Study hours this week",
  "terjadwal": "scheduled",
  "dari sesi yang sudah jalan": "from sessions already held",
  "Sesi minggu ini": "Sessions this week",
  "sesi lagi": "sessions to go",
  "semua sudah jalan": "all done",
  "PR belum disetor": "Homework not submitted",
  "ketuk kartu PR di bawah": "tap the homework card below",
  "aman, tidak ada tunggakan": "all clear, nothing pending",
  "Rata-rata skill": "Average skill",
  "belum dinilai pengajar": "not graded by the teacher yet",
  "Progres": "Progress",
  "Dinilai pengajar": "Graded by the teacher",
  "Bagikan progres": "Share progress",
  "Tersalin": "Copied",
  "Gagal": "Failed",
  "Bagikan": "Share",
  "Cetak kartu progres": "Print progress card",
  "Rata-rata": "Average",
  "Detail": "Details",
  "tugas menunggu dikerjakan": "assignments waiting to be done",
  "Kelas": "Class",
  "PR lain di tab Tugas": "more homework in the Assignments tab",
  "Materi Terbaru": "Latest Materials",
  "dari pengajar": "from your teacher",
  "Peringkat Kelas": "Class Leaderboard",
  "Kamu peringkat": "You're ranked",
  "dari": "of",
  "Kamu": "You",

  /* ── Sesi Mendatang (beranda) ───────────────────────────────────────────── */
  "Sesi Mendatang": "Upcoming Sessions",
  "sesi hari ini": "sessions today",
  "sesi terjadwal": "sessions scheduled",
  "semua kelas aktif": "all classes active",
  "Buka Jadwal": "Open Schedule",
  "Ringkas": "Collapse",
  "Lihat semua": "See all",
  "Masuk Kelas": "Join Class",

  /* ── Halaman Jadwal ─────────────────────────────────────────────────────── */
  "Jadwal Kelas": "Class Schedule",
  "sesi mendatang": "upcoming sessions",
  "sudah lewat": "already held",
  "Total minggu ini": "Total this week",
  "Keluar layar penuh": "Exit full screen",
  "Layar penuh": "Full screen",
  "Keluar layar penuh (Esc)": "Exit full screen (Esc)",
  "Layar penuh (F)": "Full screen (F)",
  "Tidak ada sesi di hari ini": "No sessions today",
  "Tidak ada sesi minggu ini": "No sessions this week",
  "Pakai panah di atas buat lihat hari lain.": "Use the arrows above to see another day.",
  "Pakai panah di atas buat lihat minggu lain.": "Use the arrows above to see another week.",
  "Jadwal Tetap (Kelas Grup)": "Fixed Schedule (Group Class)",
  "Jadwal tetap": "Fixed schedule",
  "Bahasa": "Language",
  "Presensi": "Attendance",
  "Hadir": "Present",
  "Izin": "Excused",
  "Sakit": "Sick",
  "Alpa": "Absent",
  "Dibatalkan": "Cancelled",
  "Hangus": "Forfeited",
  "Sudah lewat": "Past",
  "Libur nasional / cuti bersama": "National holiday / collective leave",
  "Pertemuan": "Meeting",
  "Materi sesi": "Session material",
  "Rekaman": "Recording",

  /* ── Detail kelas ───────────────────────────────────────────────────────── */
  "Kembali ke Beranda": "Back to Home",
  "Sesi pratinjau sudah kedaluwarsa": "The preview session has expired",
  "Sesi kamu sudah berakhir": "Your session has ended",
  "Jadwal, materi, dan daftar level di bahasa ini tidak bisa dimuat sampai kamu masuk lagi. Yang tampil di halaman ini data terakhir yang sempat tersimpan.":
    "Schedules, materials, and the level list for this language can't be loaded until you sign in again. What you see here is the last saved data.",
  "Muat Ulang": "Reload",
  "Masuk Lagi": "Sign In Again",
  "menit/sesi": "minutes/session",
  "Paket": "Package",
  "Pengajar": "Teacher",
  "Pengajar belum di-assign. Hubungi admin untuk dipasangkan.": "No teacher assigned yet. Contact the admin to get matched.",
  "Progress Sesi": "Session Progress",
  "Sisa": "Left",
  "lagi di level ini": "left at this level",
  "Semua sesi di level ini sudah selesai": "All sessions at this level are done",
  "Sesi Berikutnya": "Next Session",
  "menunggu konfirmasi pengajar": "waiting for the teacher's confirmation",
  "Mau ubah atau batalkan jadwal? Kabari pengajar di grup kelas ya.": "Need to move or cancel a session? Let your teacher know in the class group.",
  "Chat Admin": "Chat Admin",
  "Belum ada sesi terjadwal": "No session scheduled yet",
  "Hubungi admin untuk menjadwalkan sesi berikutnya.": "Contact the admin to schedule your next session.",
  "Memuat…": "Loading…",
  "Progress": "Progress",
  "Kuis": "Quiz",
  "Rapor": "Report",

  /* ── Tab Progress ───────────────────────────────────────────────────────── */
  "sesi berjalan": "sessions held",
  "Kehadiran": "Attendance rate",
  "belum berjalan": "not held yet",
  "Belum jalan": "Not held yet",
  "Kemampuan 4 Skill · CEFR": "4 Skills · CEFR",
  "Cetak": "Print",
  "Pengajar belum mengisi penilaian skill": "Your teacher hasn't filled in the skill assessment",
  "Penilaian muncul di sini setelah pengajar mengisi Catatan Progress": "The assessment shows up here once the teacher fills in the Progress Notes",
  "dari 5.0": "out of 5.0",
  "sebelumnya": "previously",
  "Pemula": "Beginner",
  "Dasar": "Elementary",
  "Menengah": "Intermediate",
  "Menengah Atas": "Upper Intermediate",
  "Mahir": "Advanced",
  "Perjalanan Belajar": "Learning Journey",
  "Belum ada sesi yang selesai": "No completed session yet",
  "Setiap sesi selesai, laporan pengajar (topik, PR, recording) tampil di sini": "After each session, the teacher's report (topic, homework, recording) shows up here",
  "Nilai kuis": "Quiz score",
  "Topik": "Topic",
  "PR": "Homework",
  "Tonton Recording": "Watch Recording",

  /* ── Tab Materi ─────────────────────────────────────────────────────────── */
  "Materi belajar": "Learning material",
  "Materi Belajar": "Learning Material",
  "Slide Materi": "Material Slides",
  "Dokumen": "Document",
  "Slide": "Slides",
  "Lampiran": "Attachment",
  "Recording Sesi": "Session Recording",
  "slide": "slides",
  "materi": "materials",
  "Yang dipelajari": "What you'll learn",
  "Catatan Materi": "Material Notes",
  "Catatan": "Notes from",
  "Pengumpulan & penilaiannya ada di tab Tugas.": "Submission & grading live in the Assignments tab.",
  "Materi Sesi": "Session Materials",
  "Belum ada materi untuk sesi ini": "No materials for this session yet",
  "Rekaman, berkas, & catatan sesi ini akan muncul di sini setelah sesinya dijalankan pengajar.":
    "The recording, files, and notes for this session will appear here once your teacher has held it.",
  "Pengajar belum melampirkan berkas atau tautan di sesi ini.": "Your teacher hasn't attached any file or link to this session.",
  "Materi & catatan akan muncul di sini setelah pengajar mengisinya.": "Materials & notes will appear here once your teacher fills them in.",
  "Sesi ini sudah berjalan": "This session has been held",
  "Belum dijadwalkan": "Not scheduled yet",
  "belum dijadwalkan": "not scheduled yet",
  "Terjadwal": "Scheduled",
  "Menunggu laporan pengajar": "Waiting for the teacher's report",
  "Menunggu konfirmasi pengajar": "Waiting for the teacher's confirmation",
  "Buka materi sesi": "Open materials for session",
  "Materi Umum": "General Materials",
  "Perjalanan Kelas": "Class Journey",
  "Belum ada sesi di kelas ini": "No sessions in this class yet",
  "Hubungi admin untuk menjadwalkan sesi pertamamu": "Contact the admin to schedule your first session",
  "Tampilkan": "Show",
  "Sesi Dibatalkan": "Cancelled Sessions",
  "Alasan": "Reason",

  /* ── Tab Kuis & Tugas ───────────────────────────────────────────────────── */
  "Rincian per Kuis": "Quiz Breakdown",
  "poin": "points",
  "benar": "correct",
  "salah": "wrong",
  "Klik kuis untuk melihat pembahasan tiap soal beserta catatan perbaikannya.": "Tap a quiz to see the explanation for each question and its correction notes.",
  "Belum ada tugas": "No assignments yet",
  "PR yang diberikan pengajar setelah sesi akan muncul di sini, lengkap dengan tempat menyetornya.":
    "Homework your teacher gives after a session shows up here, along with where to submit it.",
  "Sudah disetor": "Submitted",
  "Belum disetor": "Not submitted",
  "Sudah dinilai": "Graded",
  "Setoran kamu": "Your submission",
  "Buka lampiran": "Open attachment",
  "Penilaian pengajar": "Teacher's assessment",
  "Tulis jawabanmu di sini…": "Write your answer here…",
  "…atau tempel link (Google Docs, Drive, dll)": "…or paste a link (Google Docs, Drive, etc.)",
  "Lampirkan file (foto / PDF)": "Attach a file (photo / PDF)",
  "Perbarui setoran": "Update submission",
  "Setor tugas": "Submit assignment",
  "Batal": "Cancel",

  /* ── Tab Rapor ──────────────────────────────────────────────────────────── */
  "Belum ada rapor yang diterbitkan": "No report card published yet",
  "Pengajar menerbitkan Rapor Tengah (± sesi 8) dan Rapor Akhir di akhir program":
    "Your teacher publishes a Mid-term Report (around session 8) and a Final Report at the end of the program",
  "Sertifikat Penyelesaian": "Certificate of Completion",
  "Selamat! 🎉 Program": "Congratulations! 🎉 Your",
  "sudah selesai — sertifikatmu siap diunduh.": "program is complete — your certificate is ready to download.",
  "Unduh Sertifikat": "Download Certificate",
  "Rapor Tengah": "Mid-term Report",
  "Rapor Akhir": "Final Report",
  "Diterbitkan": "Published",
  "Komentar Pengajar": "Teacher's Comment",
  "Rekomendasi": "Recommendation",

  /* ── Tab Kelas & Materi ─────────────────────────────────────────────────── */
  "Cari bahasa…": "Search languages…",
  "Hapus pencarian": "Clear search",
  "Kelas Kamu": "Your Classes",
  "Berjalan": "Ongoing",
  "Tidak ada kelas di filter ini": "No class matches this filter",
  "Belum terjadwal": "Not scheduled yet",
  "Belum ditentukan": "Not assigned yet",
  "Kelas selesai": "Class completed",
  "Sedang berjalan": "In progress",
  "Sesi Selesai": "Sessions Completed",
  "Sesi & Rekaman": "Sessions & Recordings",
  "Silabus Level": "Level Syllabus",
  /* [beranda-tanpa-tab-mandiri-v1] tab "Belajar Mandiri" dicabut — copy-nya tak lagi
     boleh menyuruh siswa membuka tab yang sudah tak ada. */
  "Lingbook kamu ada di menu Perpustakaan. Atau daftar kelas live di bawah.":
    "Your Lingbook lives in the Library menu. Or sign up for a live class below.",

  /* ── Pengaturan, Kosakata Saya & Deck ───────────────────────────────────── */
  "+ artinya sendiri. Baris tanpa kata/arti dilewati.": "+ its meaning yourself. Rows without a word/meaning are skipped.",
  "1 hari": "1 day",
  "1 jam": "1 hour",
  "12 bulan terakhir": "last 12 months",
  "15 menit": "15 minutes",
  "3 jam": "3 hours",
  "5 tahun terakhir": "last 5 years",
  "7 hari terakhir": "last 7 days",
  "8 minggu terakhir": "last 8 weeks",
  "AI sedang menyusun deck…": "AI is building your deck…",
  "Aktif sekarang": "Active now",
  "Aktifkan subtitle bawaan saat memutar rekaman.": "Turn on built-in subtitles when playing a recording.",
  "Akurasi": "Accuracy",
  "Analisa": "Analytics",
  "Arti": "Meaning",
  "Arti (Bahasa Indonesia)": "Meaning (Indonesian)",
  "Balik kartu": "Flip card",
  "Baru": "New",
  "Bayar Sekarang": "Pay Now",
  "Belum ada data. Simpan kosakata saat menonton untuk melihat progresmu.": "No data yet. Save words while watching to see your progress.",
  "Belum ada deck": "No deck yet for",
  "Belum ada deck komunitas untuk bahasa ini. Jadilah kontributor pertama — aktifkan": "No community deck for this language yet. Be the first contributor — turn on",
  "Belum ada kata baru dikuasai sesi ini. Kata jadi “Dikuasai” setelah beberapa kali kamu nilai “Bagus”/“Mudah” di hari yang berbeda — tiap ulangan benar menjadwalkannya makin jauh sampai jaraknya mencapai": "No word became Mastered this session. A word turns “Mastered” after you rate it “Good”/“Easy” on several different days — each correct review pushes it further out until the interval reaches",
  "Belum ada kata tersimpan": "No saved words yet",
  "Belum ada kata tersimpan untuk bahasa ini. Simpan kata saat menonton dulu, lalu kembali ke sini.": "No saved words for this language yet. Save some while watching, then come back here.",
  "Belum ada paket aktif": "No active package yet",
  "Belum ada transaksi. Riwayat pembayaran kelas & produk digital kamu bakal muncul di sini.": "No transactions yet. Payments for your classes & digital products will show up here.",
  "Belum direview": "Not reviewed",
  "Belum verifikasi": "Not verified",
  "Bio singkat": "Short bio",
  "Buat Manual": "Build Manually",
  "Buat deck manual": "Build a deck manually",
  "Buat lewat salah satu tombol di atas.": "Create one with a button above.",
  "Cara kerja indikator Dikuasai": "How the Mastered indicator works",
  "Cara sebuah kata jadi “Dikuasai”": "How a word becomes “Mastered”",
  "Ceritakan sedikit tentang dirimu & tujuan belajarmu...": "Tell us a bit about yourself & your learning goals...",
  "Cicilan Berjalan": "Ongoing Installments",
  "Contoh": "Example",
  "Contoh kalimat (opsional)": "Example sentence (optional)",
  "Daftar kelas dulu yuk — paket yang sudah dibayar bakal muncul di sini.": "Enroll in a class first — packages you've paid for will show up here.",
  "Dari Video": "From a Video",
  "Dari kata yang kamu simpan": "From the words you saved",
  "Deck": "Decks",
  "Deck Komunitas": "Community Decks",
  "Deck Saya": "My Decks",
  "Deck dari video": "Deck from a video",
  "Deck ini kosong.": "This deck is empty.",
  "Deck saya": "My deck",
  "Deck tematik AI, dari video, buatan sendiri & komunitas": "AI themed decks, from videos, your own & the community's",
  "Deck tematik dibuatkan AI": "A themed deck built by AI",
  "Dengar": "Listen",
  "Dibagikan ke komunitas": "Shared with the community",
  "Dibagikan ke komunitas — klik untuk jadikan privat": "Shared with the community — click to make it private",
  "Dikuasai": "Mastered",
  "Diulang": "Reviewed",
  "Dorongan belajar setiap hari.": "A daily nudge to keep learning.",
  "Email": "Email",
  "Email & Login": "Email & Login",
  "Email H-1 sebelum sesi live dimulai.": "An email one day before a live session starts.",
  "Foto Profil": "Profile Photo",
  "Gagal membuat deck.": "Couldn't build the deck.",
  "Ganti foto": "Change photo",
  "Generate AI": "Generate with AI",
  "Generate deck": "Generate deck",
  "Generate deck by AI": "Generate a deck with AI",
  "Generate ulang": "Generate again",
  "Hanya kamu yang bisa melihat deck ini.": "Only you can see this deck.",
  "Hapus": "Remove",
  "Hapus Akun": "Delete Account",
  "Hapus deck": "Delete deck",
  "Hapus kartu": "Remove card",
  "Hubungi Admin": "Contact Admin",
  "Informasi Pribadi": "Personal Information",
  "Ingatkan aku untuk belajar setiap hari.": "Remind me to study every day.",
  "Isi kata": "Fill in the",
  "JPG atau PNG, maksimal 2MB.": "JPG or PNG, 2MB max.",
  "Jaraknya dihitung dalam hari, jadi mengulang kata yang sama berkali-kali di hari yang sama tak mempercepat — kartu baru jatuh tempo lagi setelah jaraknya lewat. Butuh beberapa hari review benar yang konsisten. Nilai": "The interval is counted in days, so repeating the same word many times on one day doesn't speed it up — the card is only due again once the interval passes. It takes a few days of consistent correct reviews. Rating",
  "Jatuh tempo": "Due",
  "Judul deck": "Deck title",
  "Jumlah kartu": "Number of cards",
  "Kamu bisa mengulang lebih awal kapan saja.": "You can review ahead anytime.",
  "Kamu mereview": "You reviewed",
  "Kartu": "Cards",
  "Kata": "Words",
  "Kata itu akan muncul di sini sebagai flashcard untuk dihafal.": "The word will show up here as a flashcard to memorize.",
  "Kata sandi baru": "New password",
  "Keamanan": "Security",
  "Keluar dari Akun": "Sign Out",
  "Kembali": "Back",
  "Kerja bagus — kamu mereview": "Nice work — you reviewed",
  "Ketuk kartu untuk lihat arti": "Tap the card to see the meaning",
  "Konfirmasi sandi baru": "Confirm new password",
  "Kosakata dari video": "Words from a video",
  "Kosongkan": "Clear all",
  "Kota": "City",
  "Lanjut ke rekaman berikutnya secara otomatis.": "Continue to the next recording automatically.",
  "Laporan mingguan": "Weekly report",
  "Level": "Level",
  "Main Kuis Arti Kata": "Play the Meaning Quiz",
  "Masuk dulu untuk membuat & membagikan deck.": "Sign in to create & share decks.",
  "Materi & rekaman baru": "New materials & recordings",
  "Membuat invoice…": "Creating invoice…",
  "Menunggu Pembayaran": "Awaiting Payment",
  "Menyimpan...": "Saving...",
  "Menyusun ulang…": "Rebuilding…",
  "Metode Pembayaran": "Payment Method",
  "Minimal 8 karakter": "At least 8 characters",
  "Mis. \"Frasa favoritku\"": "e.g. \"My favorite phrases\"",
  "Mis. \"Kosakata vlog masak\"": "e.g. \"Cooking vlog words\"",
  "Mis. \"makanan & restoran\", \"wawancara kerja\"…": "e.g. \"food & restaurants\", \"job interview\"…",
  "Mulai review": "Start review",
  "Nama Lengkap": "Full Name",
  "Nama Panggilan": "Nickname",
  "Nomor WhatsApp": "WhatsApp Number",
  "Notifikasi ke nomor WhatsApp kamu.": "Notifications to your WhatsApp number.",
  "Paket Aktif": "Active Package",
  "Paket Aktif · Cicilan": "Active Package · Installments",
  "Panggilan": "Nickname",
  "Pelajari": "Study",
  "Pembayaran online via Xendit": "Online payment via Xendit",
  "Penawaran paket dan bahasa baru.": "Package offers and new languages.",
  "Pengingat harian": "Daily reminder",
  "Pengingat jadwal sesi": "Session schedule reminder",
  "Pengingat sesi via WA": "Session reminder via WhatsApp",
  "Perangkat aktif": "Active devices",
  "Perbarui Sandi": "Update Password",
  "Pilih atau ketik tema — AI membuatkan deck kosakata": "Pick or type a theme — AI builds a",
  "Pilih bahasa": "Pick a language",
  "Pilih minimal satu kata.": "Pick at least one word.",
  "Pilih semua": "Select all",
  "Pratinjau": "Preview",
  "Privat": "Private",
  "Privat — klik untuk bagikan ke komunitas": "Private — click to share with the community",
  "Progres hari ini": "Today's progress",
  "Promo & info kelas baru": "Promos & new class info",
  "Publik": "Public",
  "Push (Aplikasi)": "Push (App)",
  "Push 15 menit sebelum sesi.": "A push 15 minutes before the session.",
  "Putar otomatis": "Autoplay",
  "QRIS, transfer bank (VA), e-wallet, & kartu. Linguo tidak menyimpan data kartumu.": "QRIS, bank transfer (VA), e-wallet & cards. Linguo never stores your card details.",
  "Review": "Review",
  "Review Harian": "Daily Review",
  "Review lagi": "Review again",
  "Ringkasan progres belajar tiap Minggu.": "A summary of your progress every Sunday.",
  "Riwayat Tagihan": "Billing History",
  "Saat menonton, ketuk kata mana pun di transkrip lalu tekan": "While watching, tap any word in the transcript then press",
  "Saat pengajar mengunggah materi atau rekaman.": "When your teacher uploads material or a recording.",
  "Seberapa awal sebelum sesi live.": "How early before a live session.",
  "Seberapa baik kamu mengingatnya?": "How well did you remember it?",
  "Sedang belajar": "Learning",
  "Semua bahasa": "All languages",
  "Semua kartu sudah diulang": "All cards reviewed",
  "Sesi akan dimulai": "Session about to start",
  "Sesi login kamu saat ini.": "Your current sign-in session.",
  "Sesi selesai!": "Session complete!",
  "Simpan": "Save",
  "Simpan deck": "Save deck",
  "Siswa lain bisa melihat & mempelajari deck ini — namamu tampil sebagai kontributor.": "Other students can see & study this deck — your name appears as the contributor.",
  "Statistik & progres belajarmu": "Your stats & learning progress",
  "Sudah masuk Kosakata Saya": "Added to My Vocabulary",
  "Susun deck dari kata yang kamu simpan saat menonton — centang kata yang mau dimasukkan.": "Build a deck from the words you saved while watching — tick the ones to include.",
  "Susun kartu sendiri": "Write your own cards",
  "Tambah Kelas Baru": "Add a New Class",
  "Tambah kartu": "Add card",
  "Tambahkan ke Kosakata Saya": "Add to My Vocabulary",
  "Tambahkan lapisan keamanan ekstra saat login.": "Add an extra layer of security at sign-in.",
  "Tampilkan jawaban": "Show answer",
  "Tampilkan subtitle": "Show subtitles",
  "Tebak arti lawan waktu — poin, streak & efek suara": "Guess meanings against the clock — points, streaks & sound effects",
  "Tema": "Theme",
  "Terbayar": "Paid",
  "Terdaftar": "Registered",
  "Terhubung": "Connected",
  "Terjemahan contoh (opsional)": "Example translation (optional)",
  "Terverifikasi": "Verified",
  "Tiap kali kamu menilai kartu": "Every time you rate a card",
  "Tindakan permanen. Hubungi admin untuk memproses penghapusan.": "Permanent action. Contact the admin to process the deletion.",
  "Tips & tantangan harian": "Daily tips & challenges",
  "Total kata": "Total words",
  "Total ulangan": "Total reviews",
  "Tutup review": "Close review",
  "Ubah Kata Sandi": "Change Password",
  "Ulang lebih awal": "Review ahead",
  "Ulangi sandi baru": "Repeat the new password",
  "Unduh PDF": "Download PDF",
  "Unduh kosakata sebagai PDF": "Download vocabulary as PDF",
  "Unduh sebagai PDF (kolom kata & arti)": "Download as PDF (word & meaning columns)",
  "Verifikasi 2 langkah (2FA)": "Two-step verification (2FA)",
  "Waktu pengingat sesi": "Session reminder timing",
  "WhatsApp": "WhatsApp",
  "Zona Waktu": "Time Zone",
  "atau": "or",
  "didaftarkan": "registered",
  "dipilih": "selected",
  "hari": "days",
  "hari.": "days.",
  "jatuh tempo": "due",
  "kamu ingat. Kartu yang sudah dijadwal ulang muncul lagi saat jatuh tempo.": "you remembered. Rescheduled cards come back when they're due.",
  "kartu": "cards",
  "kartu jatuh tempo": "cards due",
  "kartu.": "cards.",
  "kata di bahasa lain": "words in other languages",
  "kata dipelajari": "words learned",
  "kata gratis": "free words",
  "kata itu dihitung": "the word counts as",
  "kata naik jadi “Dikuasai”": "words became “Mastered”",
  "kata tersimpan": "words saved",
  "kata • hafalan dengan pengulangan berjarak": "words • memorize with spaced repetition",
  "lagi": "more",
  "lengkap dengan arti & contoh kalimat.": "vocabulary deck complete with meanings & example sentences.",
  "mengembalikannya ke awal.": "sends it back to the start.",
  "saat review, jadwal munculnya kembali makin jauh (1 hari → beberapa hari → berminggu-minggu). Begitu jaraknya mencapai": "during a review, the next appearance is pushed further out (1 day → a few days → weeks). Once the interval reaches",
  "sekarang": "now",
  "selesaikan dalam 24 jam": "complete it within 24 hours",
  "sesi terpakai": "sessions used",
  "sisa": "remaining",
  "sudah dikuasai": "mastered",
  "yang dibagikan siswa lain — nama kontributor tercantum di tiap deck.": "decks shared by other students — the contributor's name is on each deck.",
  "“Bagus”": "“Good”",
  "“Lagi”": "“Again”",
  "“Mudah”": "“Easy”",

  /* ── Sertifikat & Simulasi Tes ──────────────────────────────────────────── */
  "4 skill lengkap · penilaian AI": "All 4 skills · AI grading",
  "Asli & diterbitkan oleh Linguo": "Authentic & issued by Linguo",
  "Begitu 16 sesi di satu sublevel tuntas, sertifikatnya terbit otomatis di tab ini — misal selesai A1.1 langsung lanjut A1.2. Kalau evaluasi pengajar menyatakan kamu sudah mampu, sublevel boleh dilompati.": "Once the 16 sessions of a sublevel are done, the certificate is issued automatically in this tab — finish A1.1 and you move straight to A1.2. If your teacher's assessment says you're ready, a sublevel can be skipped.",
  "Beli Paket": "Buy Package",
  "Beli sekali, akses selamanya.": "Pay once, access forever.",
  "Belum Terbit": "Not Issued Yet",
  "Belum ada di kategori ini": "Nothing in this category yet",
  "Belum ada jawaban benar": "No correct answers yet",
  "Belum ada sertifikat": "No certificates yet",
  "Belum ada sertifikat di kategori ini.": "No certificate in this category yet.",
  "Belum ada simulasi yang tersedia. Cek lagi nanti ya!": "No simulation available yet. Check back later!",
  "Belum dinilai": "Not graded yet",
  "CEFR (Common European Framework of Reference) adalah standar internasional untuk mengukur kemampuan berbahasa — dari A1 (pemula) sampai C2 (setara penutur asli). Linguo memakai standar yang sama, lalu memecah tiap level jadi sublevel 16 sesi.": "CEFR (Common European Framework of Reference) is the international standard for measuring language ability — from A1 (beginner) to C2 (near-native). Linguo follows the same standard, then splits each level into 16-session sublevels.",
  "Coba pilih kategori lain di atas.": "Try another category above.",
  "Diberikan kepada": "Awarded to",
  "Gagal membuat PDF. Coba lagi sebentar ya.": "Couldn't create the PDF. Please try again in a moment.",
  "Grafik level CEFR A1 sampai B2 beserta sublevelnya": "Chart of CEFR levels A1 to B2 and their sublevels",
  "Halaman verifikasi publik dengan QR code sedang disiapkan. Untuk konfirmasi keaslian, hubungi tim Linguo dengan menyebutkan No. Sertifikat di atas.": "A public verification page with a QR code is on the way. To confirm authenticity, contact the Linguo team quoting the certificate number above.",
  "Jam Belajar": "Study Hours",
  "Kamu di sini": "You are here",
  "Lihat kunci jawaban": "Show the answer key",
  "Coba dulu, baru cocokkan": "Try first, then check",
  "Tutup lagi": "Hide again",
  "Sembunyikan kunci jawaban": "Hide the answer key",
  "Kerjakan latihan": "Do the exercises",
  /* [ebook-panduan-tour-v1] Panduan berpandu di reader e-book. */
  "Cara memakai reader ini": "How to use this reader",
  "Tujuh langkah singkat, kurang dari satu menit. Kamu bisa membukanya lagi kapan saja.": "Seven quick steps, under a minute. You can reopen it any time.",
  "Tekan Esc untuk keluar, panah kiri/kanan untuk berpindah langkah.": "Press Esc to leave, left/right arrows to move between steps.",
  "Lompat lewat daftar isi": "Jump around with the contents",
  "Semua unit modul terdaftar di sini beserta nomor halamannya — ketuk satu unit untuk langsung ke sana, tanpa membalik satu per satu.": "Every unit is listed here with its page number — tap one to go straight there instead of flipping page by page.",
  "Berpindah halaman": "Moving between pages",
  "Pakai panah untuk membalik satu halaman, tarik penggeser untuk menyusur cepat, atau ketuk nomor halamannya lalu ketik halaman yang kamu tuju.": "Use the arrows to turn one page, drag the slider to scan quickly, or tap the page number and type the page you want.",
  "Papan tik: ← dan →. Di HP: geser layar seperti membalik kertas.": "Keyboard: ← and →. On a phone: swipe like turning paper.",
  "Memperbesar tulisan": "Making the text bigger",
  "Angka persen itu bisa diketik langsung, jadi tak perlu menekan + berkali-kali. Tombol di sebelahnya mengembalikan halaman supaya pas satu layar.": "The percentage can be typed in directly, so you never have to tap + over and over. The button next to it fits the spread back to the screen.",
  "Cubit dua jari di trackpad atau layar sentuh, atau tekan Ctrl/⌘ dengan + − 0.": "Pinch with two fingers on a trackpad or touchscreen, or press Ctrl/⌘ with + − 0.",
  "Ketuk kata untuk mendengarnya": "Tap a word to hear it",
  "Ketuk kata mana pun di halaman: kamu akan mendengar pelafalannya sekaligus melihat artinya dalam bahasa Indonesia.": "Tap any word on the page: you will hear how it is pronounced and see what it means.",
  "Kunci jawaban ditutup dulu": "The answer key stays covered",
  "Kunci jawaban di modul sengaja ditutup tirai. Kerjakan dulu soalnya, baru ketuk kotaknya untuk mencocokkan.": "Answer keys in the module are deliberately hidden behind a curtain. Do the exercise first, then tap the box to check.",
  "Kerjakan latihannya di layar": "Do the exercises on screen",
  "Di halaman yang ada blok LATIHAN-nya, tombol ini muncul di bilah bawah. Soalnya dikerjakan langsung di sini dan dinilai otomatis — tanpa kertas.": "On pages that carry an EXERCISES block, this button appears in the bottom bar. You answer right here and it is checked automatically — no paper needed.",
  "Panduan ini selalu ada di sini": "This guide is always here",
  "Lupa salah satu langkah? Buka lagi panduannya dari tombol ini kapan saja.": "Forgot a step? Reopen the guide from this button any time.",
  "Halaman ini ada latihannya": "This page has exercises",
  "Ketuk tombol ini untuk mengerjakan soal unit ini langsung di layar. Jawabanmu dicek otomatis, dan yang belum pas bisa diulang.": "Tap this button to work through this unit's exercises on screen. Your answers are checked automatically, and anything you miss can be redone.",
  "Panduan pemakaian": "How to use this",
  "Tutup panduan": "Close the guide",
  "Lewati panduan": "Skip the guide",
  "Kerjakan latihan unit ini": "Do this unit's exercises",
  "Latihan": "Exercises",
  "Ketuk kata di bawah untuk menyusun kalimat": "Tap the words below to build the sentence",
  "Hapus satu kata": "Remove one word",
  "Belum pas": "Not quite",
  "Jawabanku juga benar": "My answer is right too",
  "Ulangi yang salah": "Redo the wrong ones",
  "Kembali membaca": "Back to reading",
  "Yang belum pas bukan gagal — itu justru daftar yang paling layak diulang.": "What you missed is not failure — it is exactly the list worth repeating.",
  "Semua benar. Lanjut ke unit berikutnya.": "All correct. On to the next unit.",
  "Lihat isi bagian ini": "Show what is inside",
  "Kamu perlu masuk dulu untuk mengerjakan simulasi.": "You need to sign in first to take a simulation.",
  "Lanjut Belajar": "Keep Learning",
  "Lanjutkan": "Continue",
  "Laporan Skor": "Score Report",
  "Level CEFR": "CEFR Level",
  "Level tersedia": "Levels available",
  "Lihat Jadwal": "View Schedule",
  "Lihat peta level A1–B2": "See the A1–B2 level map",
  "Masih dalam pengembangan. Segera hadir!": "Still in development. Coming soon!",
  "Membuat PDF…": "Creating PDF…",
  "Memuat riwayat skor…": "Loading score history…",
  "Mengerti": "Got it",
  "Mulai": "Start",
  "Nilai Akhir": "Final Score",
  "No. Sertifikat": "Certificate No.",
  "Penilaian Kemampuan": "Skills Assessment",
  "Peta level di Linguo": "The level map at Linguo",
  "Pilih sertifikat": "Pick a certificate",
  "Program": "Program",
  "Progres tersimpan": "Progress saved",
  "Progress menuju sertifikat": "Progress toward the certificate",
  "Riwayat Skor": "Score History",
  "Satu sublevel = satu sertifikat.": "One sublevel = one certificate.",
  "Sedang dikerjakan": "In progress",
  "Segera": "Soon",
  "Segera Hadir": "Coming Soon",
  "Sertifikat Terverifikasi": "Verified Certificate",
  "Sertifikat terbit otomatis setelah kamu menuntaskan satu sublevel (16 sesi).": "A certificate is issued automatically once you finish a sublevel (16 sessions).",
  "Sesi Tersisa": "Sessions Left",
  "Simulasi": "Simulation",
  "Sublevel": "Sublevels",
  "Sudah beli? Akses terhubung ke email pembelian — kamu login sebagai": "Already bought it? Access is tied to the purchase email — you are signed in as",
  "TOEFL & IELTS — latihan dengan penilaian AI": "TOEFL & IELTS — practice with AI grading",
  "Tambah ke LinkedIn": "Add to LinkedIn",
  "Tampilkan lebih sedikit": "Show less",
  "Tanggal": "Date",
  "Tanggal terbit": "Issue date",
  "Target Level": "Target Level",
  "Teks sertifikat disalin ke clipboard ✓": "Certificate text copied to clipboard ✓",
  "Tentang CEFR": "About CEFR",
  "Tiap balok = 1 sublevel = 16 sesi. Semakin tinggi baloknya, semakin dalam materinya.": "Each bar = 1 sublevel = 16 sessions. The taller the bar, the deeper the material.",
  "Tidak dijawab": "Not answered",
  "Tinggal": "Just",
  "Total sesi": "Total sessions",
  "Unduh laporan skor": "Download score report",
  "Unduh sertifikat": "Download certificate",
  "Verifikasi keaslian": "Verify authenticity",
  "bagian": "sections",
  "dalam proses": "in progress",
  "di Linguo.": "at Linguo.",
  "pengerjaan": "attempts",
  "pengerjaan tersimpan — klik untuk lihat skor & pembahasannya lagi": "saved attempts — tap one to see its score & explanations again",
  "sama": "same",
  "sekali bayar": "one-time payment",
  "soal": "questions",
  "sublevel": "sublevels",
  "terbit": "issued",
  "untuk membuka sertifikat ini.": "to unlock this certificate.",
  "atas keberhasilan menuntaskan program privat Bahasa": "for successfully completing the private program in",
  "atas keberhasilan menuntaskan program reguler Bahasa": "for successfully completing the regular program in",
  "telah menyelesaikan petualangan belajar Bahasa": "has completed a learning adventure in",
  "dengan penuh semangat": "with great enthusiasm",
  "atas penyelesaian program persiapan tes Bahasa": "for completing the test preparation program in",
  "atas keberhasilan menuntaskan program Bahasa": "for successfully completing the program in",
  "Sertifikat Petualang Cilik": "Little Explorer Certificate",
  "Sertifikat Persiapan Tes": "Test Preparation Certificate",
  "IELTS & TOEFL Prep": "IELTS & TOEFL Prep",
  "Program Private tersedia sampai level tertinggi B1.": "The Private program is available up to B1, its highest level.",
  "IELTS & TOEFL": "IELTS & TOEFL",
  "Elementary": "Elementary",
  "Cukup": "Fair",
  "Baik": "Good",

  /* ── Grup Kelas, Watch & Learn, Lingbook ────────────────────────────────── */
  "Bahasa saya": "My language",
  "Balas": "Reply",
  "Batal membalas": "Cancel reply",
  "Belajar bahasa dari konten yang kamu suka": "Learn a language from content you actually enjoy",
  "Belum ada pesan di grup ini. Sapa pengajarmu duluan boleh, kok.": "No messages in this group yet. Feel free to say hi to your teacher first.",
  "Belum ada video ketemu": "No video found yet",
  "Belum ada video siap": "No ready video yet",
  "Bersihkan pencarian": "Clear search",
  "Buang": "Discard",
  "Buka di tab baru": "Open in a new tab",
  "Buka gambar": "Open image",
  "Cari": "Search",
  "Cari Kata": "Word Search",
  "Cari video dalam bahasa": "Search videos in",
  "Coba kategori lain, ganti bahasa, atau muat ulang. Katalog cuma menampilkan video pendek (≤20 menit) & terbatas kuota harian YouTube — beberapa saat lagi biasanya kembali penuh.": "Try another category, switch language, or reload. The catalog only shows short videos (≤20 min) and is limited by YouTube's daily quota — it usually fills back up shortly.",
  "Ebook interaktif — tap tiap kata untuk cara baca, arti, dan analisa tata bahasanya.": "Interactive ebooks — tap any word for its pronunciation, meaning, and grammar breakdown.",
  "Emoji": "Emoji",
  "Foto berikutnya": "Next photo",
  "Foto sebelumnya": "Previous photo",
  "Gagal terkirim": "Failed to send",
  "Grup kelas gagal dimuat": "Couldn't load your class groups",
  "Grup kelasmu belum tersambung": "Your class group is not connected yet",
  "Hapus semua": "Clear all",
  "Kalau kamu sudah punya grup WhatsApp kelas bersama pengajar, minta tim Linguo menyambungkannya ke akun ini — setelah itu percakapannya bisa dibaca & dibalas dari halaman ini.": "If you already have a class WhatsApp group with your teacher, ask the Linguo team to link it to this account — after that you can read & reply to it right here.",
  "Kamu bicara bahasa apa?": "What language do you speak?",
  "Keluar dari layar penuh": "Exit full screen",
  "Keluar dari layar penuh (Esc)": "Exit full screen (Esc)",
  "Kembali ke daftar grup": "Back to the group list",
  "Ketik kata dalam bahasa": "Type a word in",
  "Ketik sebuah kata lalu tekan Enter untuk melihat contohnya di video.": "Type a word then press Enter to see it used in videos.",
  "Kosakata": "Vocabulary",
  "Lanjut Menonton": "Keep Watching",
  "Lanjutkan membaca": "Continue reading",
  "Layar ini tidak bisa membaca grup kelas siswa lagi. Buka ulang “Lihat sebagai siswa” dari dashboard admin — bukan berarti siswanya tak punya grup kelas.": "This screen can no longer read the student's class groups. Reopen \"View as student\" from the admin dashboard — it does not mean the student has no class group.",
  "Lihat cara sebuah kata dipakai di kalimat nyata dari video katalog. Klik hasil untuk lompat ke momen kata itu diucapkan.": "See how a word is used in real sentences from catalog videos. Tap a result to jump to the moment it is spoken.",
  "Longgarkan filter durasi/level, muat lainnya, atau ganti kategori.": "Loosen the duration/level filter, load more, or switch category.",
  "Memuat percakapan…": "Loading conversation…",
  "Mencari…": "Searching…",
  "Mengirim…": "Sending…",
  "Mode pratinjau — kotak tulis dimatikan.": "Preview mode — the composer is disabled.",
  "Muat lainnya": "Load more",
  "Mulai membaca": "Start reading",
  "Pencarian terakhir": "Recent searches",
  "Percakapan ini grup WhatsApp kelasmu. Pesanmu tetap masuk ke grupnya, jadi pengajar & teman kelas tetap bisa membacanya dari WhatsApp.": "This conversation is your class WhatsApp group. Your messages still land in the group, so your teacher & classmates can read them from WhatsApp.",
  "Perkiraan level bahasa dari transkrip": "Estimated language level from the transcript",
  "Pesan ini dihapus": "This message was deleted",
  "Putar video": "Play video",
  "Rekomendasi untukmu": "Recommended for you",
  "Reset filter": "Reset filters",
  "Sambungan ke server terputus sebentar. Coba muat ulang; percakapan grupmu tidak ke mana-mana.": "The connection to the server dropped for a moment. Try reloading; your group conversation is not going anywhere.",
  "Sesi pratinjau sudah habis": "The preview session has expired",
  "Tak ada video cocok filter di halaman ini": "No video on this page matches the filters",
  "Terakhir dipilih": "Recently picked",
  "Terjemahan Siap": "Translation Ready",
  "Subtitle siap": "Subtitles ready",
  "Terjemahan di bawah subtitle akan ditampilkan dalam bahasa ini. Bisa diganti kapan saja lewat tombol bendera di atas.": "Translations under the subtitles will be shown in this language. You can change it anytime with the flag button above.",
  "Tidak ada bahasa cocok.": "No matching language.",
  "Tidak ada grup yang cocok dengan": "No group matches",
  "Tidak ketemu di katalog": "Not found in the catalog",
  "Tonton beberapa video dari kategori lain dulu. Begitu subtitle + terjemahannya selesai diproses, video otomatis muncul di sini — dan langsung tampil instan buat siapa pun yang membukanya.": "Watch a few videos from other categories first. Once their subtitles + translations are processed, the videos appear here automatically — and open instantly for anyone.",
  "Turun ke pesan terbaru": "Jump to the latest message",
  "anggota": "members",
  "bab": "chapters",
  "bahasa yang dipelajari": "learning language",
  "belum ada di transkrip video": "is not in the saved transcripts for",
  "contoh ditemukan": "examples found",
  "dari riwayat": "from history",
  "grup WhatsApp": "WhatsApp group",
  "yang tersimpan. Coba kata lain, atau tambah videonya ke katalog dulu.": "videos yet. Try another word, or add the video to the catalog first.",
  "Populer": "Popular",
  "Kreator": "Creators",
  "Hiburan": "Entertainment",
  "Kartun": "Cartoons",
  "Musik": "Music",
  "Berita": "News",
  "Kuliner": "Food",
  "Olahraga": "Sports",
  "Anak": "Kids",
  "Semua durasi": "Any length",
  "< 5 mnt": "< 5 min",
  "5–10 mnt": "5–10 min",
  "10–20 mnt": "10–20 min",

  /* ── Belajar Mandiri (LessonPlayer) & pembaca e-book ────────────────────── */
  "Audio belum tersedia untuk sesi ini.": "Audio is not available for this session yet.",
  "Belum ada sesi.": "No sessions yet.",
  "Benar!": "Correct!",
  "Daftar sesi": "Session list",
  "Dengar pelafalan": "Hear the pronunciation",
  "Gagal membuat invoice. Coba lagi ya.": "Couldn't create the invoice. Please try again.",
  "Gagal memuat modul": "Couldn't load the module",
  "Gambar belum diunggah untuk blok ini.": "No image has been uploaded for this block yet.",
  "Ganti level": "Switch level",
  "Halaman berikutnya": "Next page",
  "Halaman gagal digambar": "The page couldn't be rendered",
  "Halaman sebelumnya": "Previous page",
  "Hampir!": "Almost!",
  "Jawaban yang benar": "The correct answer is",
  "Kamu perlu masuk dulu untuk belajar.": "You need to sign in first to start learning.",
  "Keluar dari sesi ini?": "Leave this session?",
  "Kembali ke daftar sesi": "Back to the session list",
  "Ketuk gelembung untuk mendengar pelafalannya.": "Tap a bubble to hear how it is pronounced.",
  "Ketuk tombol putar untuk mendengar pelafalannya, lalu ulangi dengan suara.": "Tap play to hear the pronunciation, then repeat it out loud.",
  "Kosakata baru": "New vocabulary",
  "Langkah": "Step",
  "Lanjut belajar": "Keep learning",
  "Lanjut sesi berikutnya": "On to the next session",
  "Mantap, jawaban kamu tepat.": "Nice, your answer is spot on.",
  "Masuk ke akun": "Sign in",
  "Materi sesi ini belum tersedia — lagi disiapkan ya.": "This session's material isn't ready yet — we're preparing it.",
  "Materi · Dengarkan": "Material · Listen",
  "Materi · Dialog": "Material · Dialogue",
  "Materi · Gambar": "Material · Image",
  "Materi · Kosakata": "Material · Vocabulary",
  "Materi · Tabel": "Material · Table",
  "Menyiapkan modul…": "Preparing the module…",
  /* [ebook-daftar-isi-v1] + [ebook-popup-kata-v1] — reader e-book */
  "Menyusun daftar isi…": "Building the table of contents…",
  "Daftar isi": "Contents",
  "Lompat ke halaman": "Jump to page",
  /* [ebook-daftar-isi-timeline-v1] */
  "Progres baca": "Reading progress",
  "Buka halaman": "Open page",
  "Geser ke halaman": "Slide to page",
  "Modul ini tak punya judul yang bisa dibaca otomatis — pakai penggeser halaman di bilah bawah.":
    "This module has no headings we can read automatically — use the page slider in the bottom bar.",
  "Arti belum bisa dimuat": "Meaning unavailable",
  "bentuk dasar": "base form",
  "Putar kalimat": "Play sentence",
  "Dengar pelafalannya": "Hear it pronounced",
  "Ketuk kata untuk mendengar pelafalannya": "Tap a word to hear it pronounced",
  "Yang bisa dibunyikan hanya teks": "Only text can be read aloud in",
  "Perbesar": "Zoom in",
  "Periksa": "Check",
  "Perkecil": "Zoom out",
  "Pilih level": "Pick a level",
  "Pilih satu jawaban dulu": "Pick an answer first",
  "Selesai & Rangkuman": "Finish & Summary",
  "Selesaikan": "Finish",
  "Sembunyikan": "Hide",
  "Sembunyikan daftar sesi": "Hide the session list",
  "Sesi belajar": "Learning session",
  "Sesi berikutnya": "Next session",
  "Sesi tidak ditemukan.": "Session not found.",
  "Soal": "Question",
  "Tampilkan daftar sesi": "Show the session list",
  "Tekan Periksa untuk cek jawaban": "Press Check to see if you got it right",
  "Tenang, progres yang udah kamu kerjain tetap kesimpan. Kamu bisa lanjut lagi kapan aja dari daftar sesi.": "Don't worry, the progress you've made is saved. You can pick up again anytime from the session list.",
  "Terjadi kesalahan saat membuat invoice. Coba lagi ya.": "Something went wrong creating the invoice. Please try again.",
  "Tutup daftar sesi": "Close the session list",
  "Ulangi sesi": "Repeat session",
  "Ya, keluar": "Yes, leave",
  "kelar. Progress kamu udah kesimpan — lanjut ke sesi berikutnya kapan aja.": "is done. Your progress is saved — move on to the next session whenever you like.",
  "sub-level": "sublevels",

  /* ── Runner Simulasi Tes & layar hasil ──────────────────────────────────── */
  "Ada audio": "Has audio",
  "Ada teks bacaan": "Has a reading passage",
  "Akses gratis (kode promo) — sisa": "Free access (promo code) —",
  "Andalkan aturan tata bahasa, bukan sekadar bunyi kalimat yang terdengar wajar.": "Rely on grammar rules, not just what sounds natural.",
  "Angka ini": "This number is an",
  "Baca teks (passage) dengan teliti — teks ada di panel kiri dan bisa digulir.": "Read the passage carefully — it sits in the left panel and scrolls.",
  "Baca tiap kalimat dengan teliti — ini menguji tata bahasa (grammar).": "Read each sentence carefully — this tests grammar.",
  "Bagian": "Section",
  "Belajar privat 1-on-1 bareng pengajar": "Study 1-on-1 with a",
  "Belum Dikerjakan": "Not Started",
  "Belum ada jawaban yang benar pada pengerjaan ini,": "No answer was correct in this attempt,",
  "Belum ada soal di subtes ini.": "No questions in this subtest yet.",
  "Benar": "Correct",
  "Boleh kembali membaca teks kapan saja selama waktu masih ada.": "You can go back to the passage anytime while time remains.",
  "Catatan penilai": "Grader's notes",
  "Cek Mikrofon": "Microphone Check",
  "Coba lagi": "Try again",
  "Detail Tryout": "Tryout Details",
  "Dikumpulkan": "Submitted",
  "Durasi": "Duration",
  "Email (opsional)": "Email (optional)",
  "Geser untuk mengatur lebar bacaan & soal": "Drag to resize the passage & questions panes",
  "Hal": "Page",
  "Hanya yang salah": "Wrong only",
  "Hasil simulasi": "Simulation result",
  "Isi identitas dulu": "Fill in your details first",
  "Izinkan akses mikrofon saat diminta browser.": "Allow microphone access when the browser asks.",
  "Jatah habis, beli paket untuk lanjut.": "Your free attempts are used up; buy a package to continue.",
  "Jawab tiap soal sesuai informasi pada teks, bukan pengetahuan umum.": "Answer each question from the passage, not general knowledge.",
  "Jawaban & sisa waktu tersimpan otomatis. Kamu bisa membuka simulasi ini lagi dan melanjutkan dari titik ini.": "Your answers & remaining time are saved automatically. You can reopen this simulation and pick up from here.",
  "Jawabanmu": "Your answer",
  "Jumlah Bagian": "Sections",
  "Kamu akan keluar dari mode preview.": "You are about to leave preview mode.",
  "Kamu bisa merekam ulang bila belum puas dengan jawabanmu.": "You can re-record if you are not happy with your answer.",
  "Kamu boleh menjeda dan mengulang audio selama waktu masih tersedia.": "You may pause and replay the audio while time remains.",
  "Kamu sudah memakai": "You have used all",
  "Kamu terdeteksi berpindah ke aplikasi/jendela lain.": "You were detected switching to another app/window.",
  "Kamu terdeteksi berpindah tab / meninggalkan layar ujian.": "You were detected switching tabs / leaving the exam screen.",
  "Kamu terdeteksi keluar dari mode layar penuh.": "You were detected leaving full-screen mode.",
  "Kamu tidak menjawab soal ini.": "You did not answer this question.",
  "Ke Dashboard": "To the Dashboard",
  "Kembali ke Riwayat Skor": "Back to Score History",
  "Kembali ke daftar": "Back to the list",
  "Kerjakan tiap bagian secara berurutan.": "Work through each section in order.",
  "Kesempatan gratis sudah habis": "No free attempts left",
  "Ketik jawabanmu…": "Type your answer…",
  "Konsultasi via WhatsApp": "Consult via WhatsApp",
  "Kosong": "Empty",
  "Kriteria penilaian": "Grading criteria",
  "Kunci jawaban": "Correct answer",
  "Kurang tepat": "Not quite",
  "Lanjutkan Ujian (layar penuh)": "Resume Exam (full screen)",
  "Lengkapi kalimat dengan kata yang tepat:": "Complete the sentence with the right word:",
  "Lihat program persiapan tes": "See the test prep program",
  "Masih ada": "There are still",
  "Masuk / Daftar": "Sign in / Register",
  "Masuk dulu untuk mengerjakan simulasi.": "Sign in first to take the simulation.",
  "Mau skormu naik lebih cepat?": "Want your score to climb faster?",
  "Meminta izin mikrofon…": "Requesting microphone permission…",
  "Mencapai": "Reaching",
  "Mencetak / menyimpan halaman soal tidak diizinkan.": "Printing / saving the question page is not allowed.",
  "Menilai jawaban": "Grading your",
  "Menilai jawaban kamu…": "Grading your answers…",
  "Menit": "Minutes",
  "Menyiapkan…": "Preparing…",
  "Mikrofon aktif — coba bicara, bar akan bergerak.": "Microphone is live — say something and the bar will move.",
  "Mohon tunggu sebentar.": "Please wait a moment.",
  "Mulai Simulasi": "Start Simulation",
  "Mulai bagian ini": "Start this section",
  "Mulai rekam": "Start recording",
  "Nama lengkap *": "Full name *",
  "Nilai per subtes": "Score per subtest",
  "No. WhatsApp (opsional)": "WhatsApp number (optional)",
  "Nomor saat ini": "Current question",
  "Pelanggaran tercatat": "Violations recorded",
  "Pelanggaran terdeteksi": "Violation detected",
  "Pembahasan": "Explanation",
  "Pembahasan jawaban": "Answer explanations",
  "Periksa kembali tata bahasa dan ejaan sebelum lanjut.": "Re-check grammar and spelling before moving on.",
  "Perkiraan skor": "Estimated",
  "Petunjuk Bagian": "Section Instructions",
  "Petunjuk Bagian Listening": "Listening Section Instructions",
  "Petunjuk Bagian Reading": "Reading Section Instructions",
  "Petunjuk Bagian Speaking": "Speaking Section Instructions",
  "Petunjuk Bagian Structure": "Structure Section Instructions",
  "Petunjuk Bagian Writing": "Writing Section Instructions",
  "Petunjuk Pengerjaan": "Exam Instructions",
  "Pilih bagian yang salah secara tata bahasa:": "Pick the grammatically incorrect part:",
  "Pilih jawaban yang melengkapi kalimat dengan benar, atau tandai bagian yang salah.": "Pick the option that completes the sentence correctly, or mark the faulty part.",
  "Proctoring aktif": "Proctoring on",
  "Putar audio dan simak baik-baik — gunakan tombol ±10 detik untuk mengulang bagian penting.": "Play the audio and listen closely — use the ±10 second buttons to replay key parts.",
  "Rekam jawabanmu — bicara dengan jelas dan sesuai instruksi.": "Record your answer — speak clearly and follow the prompt.",
  "Rekam jawabanmu.": "Record your answer.",
  "Rekam ulang": "Record again",
  "Rekaman tersimpan": "Recording saved",
  "Rincian Bagian": "Section Breakdown",
  "Rincian per subtes tak tersimpan pada pengerjaan ini, jadi angkanya diperkirakan dari total poin.": "Per-subtest detail was not saved for this attempt, so the numbers are estimated from the total points.",
  "Saya Mengerti, Mulai Simulasi": "I Understand, Start the Simulation",
  "Sebelum mengerjakan": "Before you start",
  "Selama mengerjakan, klik kanan, blok-salin teks soal, tempel jawaban dari luar, cetak/simpan halaman, dan pintasan devtools diblokir. Yang bisa dipakai hanya tombol di layar ujian (navigasi soal, Selesaikan Subtes, dan tombol keluar).": "During the exam, right-click, selecting/copying question text, pasting answers from outside, printing/saving the page, and devtools shortcuts are blocked. Only the on-screen exam buttons work (question navigation, Finish Subtest, and the exit button).",
  "Selesaikan Subtes": "Finish Subtest",
  "Selesaikan subtes": "Finish the",
  "Semua skormu tersimpan di": "All your scores are kept in",
  "Sesi simulasi ini sudah lewat dari 24 jam, jadi otomatis dikumpulkan. Jawaban yang sempat tersimpan tetap dinilai.": "This simulation session is more than 24 hours old, so it was submitted automatically. Whatever answers were saved are still graded.",
  "Simulasi ini tidak memuat seluruh subtes ujian aslinya, jadi skor total diperkirakan proporsional.": "This simulation does not include every subtest of the real exam, so the total score is estimated proportionally.",
  "Simulasi lain": "Other simulations",
  "Simulasi selesai!": "Simulation complete!",
  "Simulasi tidak tersedia. Mungkin belum dipublikasikan, atau kamu belum punya akses paketnya.": "This simulation is unavailable. It may not be published yet, or you may not have access to its package.",
  "Sisa waktu — otomatis dikumpulkan saat habis": "Time remaining — submitted automatically when it runs out",
  "Skor AI": "AI score",
  "Skor mentah": "Raw score",
  "Skor per subtes": "Score per subtest",
  "Skormu bagus — kunci biar makin stabil": "Great score — lock it in and make it consistent",
  "Subtes": "Subtest",
  "Subtes dikerjakan": "Subtests are taken",
  "Subtes dikerjakan BERURUTAN seperti ujian aslinya (mis. Listening → Structure → Reading, atau Listening → Reading → Writing → Speaking). Subtes berikutnya baru terbuka setelah subtes sebelumnya diselesaikan, dan yang sudah selesai tidak bisa dibuka lagi.": "Subtests are taken IN ORDER like the real exam (e.g. Listening → Structure → Reading, or Listening → Reading → Writing → Speaking). The next subtest only unlocks once the previous one is finished, and a finished one cannot be reopened.",
  "Subtes terkunci minimal": "Subtest locked for at least",
  "Subtes yang diujikan": "Subtests in this exam",
  "Sudah beli paketnya? Coba muat ulang halaman ini, dan pastikan login memakai email yang sama dengan saat pembelian.": "Already bought the package? Try reloading this page, and make sure you signed in with the same email you used to purchase.",
  "Susun jawaban dengan struktur yang jelas: pembuka, isi, penutup.": "Structure your answer clearly: opening, body, closing.",
  "Tanpa batas": "No limit",
  "Tanya admin": "Ask the admin",
  "Terisi": "Answered",
  "Terkunci": "Locked",
  "Tes ini ada bagian Speaking. Pastikan mikrofon berfungsi sebelum mulai.": "This test has a Speaking section. Make sure your microphone works before you start.",
  "Tes mikrofon": "Test microphone",
  "Tiap subtes punya batas waktu sendiri dan dikunci minimal": "Each subtest has its own time limit and is locked for at least",
  "Tidak ada jawaban yang salah di subtes ini.": "No wrong answers in this subtest.",
  "Tidak ada satu pun soal yang terjawab pada pengerjaan ini,": "Not a single question was answered in this attempt,",
  "Tidak ada soal di bagian ini.": "No questions in this section.",
  "Tidak bisa mengakses mikrofon. Izinkan akses di browser lalu coba lagi.": "Can't access the microphone. Allow access in your browser and try again.",
  "Tidak bisa mengakses mikrofon. Izinkan akses mikrofon di browser.": "Can't access the microphone. Allow microphone access in your browser.",
  "Total Soal": "Total Questions",
  "Tulis esai kamu di sini…": "Write your essay here…",
  "Tulis esai sesuai instruksi dan perhatikan jumlah kata minimal.": "Write the essay as instructed and mind the minimum word count.",
  "Tulis/pilih jawaban sesuai yang kamu dengar.": "Write/pick your answer based on what you hear.",
  "Tutup preview": "Close preview",
  "Tutup simulasi?": "Close the simulation?",
  "Ujian dikerjakan dalam mode LAYAR PENUH. Berpindah tab, berpindah aplikasi/jendela lain, minimize, atau keluar dari layar penuh tercatat sebagai pelanggaran.": "The exam runs in FULL SCREEN. Switching tabs, switching to another app/window, minimizing, or leaving full screen is recorded as a violation.",
  "Unduh Laporan Skor": "Download the Score Report",
  "Unduh Sertifikat hasil simulasi (PDF)": "Download the simulation certificate (PDF)",
  "Visual soal": "Question image",
  "Ya, tutup & simpan": "Yes, close & save",
  "berurutan": "in order",
  "di bawah nilai minimum seksi": "below the section minimum",
  "dulu": "subtest first",
  "isi data berikut. Nama akan tampil di hasil pengerjaanmu.": "fill in the details below. Your name appears on your result.",
  "jadi hasilnya": "so the result is",
  "jawaban otomatis dikumpulkan.": "violations submits your answers automatically.",
  "ke skala resmi (skala": "to the official scale (the",
  "kesempatan coba gratis untuk tes ini. Beli paket untuk akses penuh tanpa batas.": "free attempts for this test. Buy a package for unlimited access.",
  "kesempatan.": "attempts.",
  "kosong": "empty",
  "materi disusun dari kelemahanmu di simulasi ini, jadwal fleksibel, plus latihan & pembahasan tiap sesi. Konsultasi gratis dulu, tanpa komitmen.": "teacher: the material is built from the weak spots in this simulation, the schedule is flexible, plus practice & review every session. Free consultation first, no commitment.",
  "menit setelah dimulai, dan subtes yang sudah diselesaikan tidak bisa dibuka lagi. Saat subtes terakhir selesai, seluruh jawaban otomatis dikumpulkan.": "minutes after it starts, and a finished subtest cannot be reopened. When the last subtest ends, all answers are submitted automatically.",
  "menit total": "minutes total",
  "menit — kamu tidak bisa pindah subtes sebelum itu (kecuali waktunya habis).": "minutes — you cannot switch subtests before then (unless time runs out).",
  "menit — sisa": "minutes — remaining",
  "pelanggaran → jawaban otomatis dikumpulkan dan ujian berakhir.": "violations → your answers are submitted automatically and the exam ends.",
  "pelanggaran → jawaban otomatis dikumpulkan.": "violations → your answers are submitted automatically.",
  "perkiraan": "estimate",
  "punya batas bawah yang bukan nol). Kerjakan ulang simulasinya untuk mendapat perkiraan skor.": "scale has a non-zero floor). Retake the simulation to get an estimated score.",
  "secara otomatis…": "answer automatically…",
  "seperti ujian aslinya": "like the real exam",
  "simulasi": "the simulation",
  "soal belum dijawab di subtes ini. Subtes yang sudah diselesaikan TIDAK bisa dibuka lagi. Yakin selesai?": "unanswered questions in this subtest. A finished subtest CANNOT be reopened. Finish anyway?",
  "soal objektif benar": "objective questions correct",
  "soal yang belum dijawab. Lengkapi semua soal dulu sebelum mengirim — cek panel Navigasi Soal (tanda merah = terlewati).": "unanswered questions. Complete them all before submitting — check the Question Navigation panel (red = skipped).",
  "soal — isi langsung di tabel": "questions — fill them in directly in the table",
  "subtes": "subtests",
  "subtes berikutnya baru terbuka setelah subtes sebelumnya diselesaikan. Tiap subtes punya batas waktu sendiri dan dikunci minimal": "the next subtest only unlocks once the previous one is finished. Each subtest has its own time limit and is locked for at least",
  "tab Simulasi Tes": "the Test Simulation tab",
  "terisi": "answered",
  "terlewati — belum dijawab": "skipped — not answered",
  "tidak dihitung di skala resmi ujian ini": "not counted on this exam's official scale",
  "tidak dikonversi": "not converted",
  "untuk mengukur posisimu — bukan skor resmi lembaga tes.": "to gauge where you stand — not an official score from the test board.",
  "IELTS mengukur kemampuan bahasa Inggris melalui empat keterampilan: Listening, Reading, Writing, dan Speaking. Kerjakan tiap bagian secara berurutan dan perhatikan sisa waktu.": "IELTS measures English ability across four skills: Listening, Reading, Writing and Speaking. Work through each section in order and keep an eye on the clock.",
  "TOEFL mengukur kemampuan bahasa Inggris akademik melalui empat keterampilan: Reading, Listening, Speaking, dan Writing. Kerjakan tiap bagian secara berurutan dan perhatikan sisa waktu.": "TOEFL measures academic English across four skills: Reading, Listening, Speaking and Writing. Work through each section in order and keep an eye on the clock.",
  "Baca teks dengan teliti, lalu jawab pertanyaan pilihan ganda / True–False–Not Given / isian sesuai informasi pada teks.": "Read the passage carefully, then answer the multiple-choice / True–False–Not Given / fill-in questions using the information in the text.",
  "Putar audio dan simak baik-baik (boleh diputar ulang), lalu jawab pertanyaannya. Tulis jawaban singkat sesuai yang kamu dengar.": "Play the audio and listen closely (replays allowed), then answer the questions. Write short answers based on what you hear.",
  "Tulis esai sesuai instruksi dan jumlah kata minimal.": "Write the essay as instructed and meet the minimum word count.",
  "Rekam jawabanmu menggunakan mikrofon. Bicara dengan jelas sesuai instruksi.": "Record your answer with the microphone. Speak clearly and follow the prompt.",
  "Soal tata bahasa (grammar). Pilih jawaban yang melengkapi kalimat dengan benar, atau temukan bagian kalimat yang salah.": "Grammar questions. Pick the option that completes the sentence correctly, or find the faulty part of the sentence.",
  "Kerjakan setiap bagian secara berurutan. Gunakan panel Navigasi Soal untuk berpindah dan memantau soal yang belum dijawab.": "Work through each section in order. Use the Question Navigation panel to move around and track unanswered questions.",
  "Pastikan semua soal sudah dijawab sebelum mengirim — soal yang terlewati ditandai merah pada navigasi.": "Make sure every question is answered before submitting — skipped questions are marked red in the navigation.",
  "Untuk bagian Speaking, izinkan akses mikrofon di browser saat diminta.": "For the Speaking section, allow microphone access in your browser when asked.",
  "Jawaban otomatis dikumpulkan ketika waktu habis, jadi pantau terus sisa waktu di pojok atas.": "Answers are submitted automatically when time runs out, so keep watching the timer at the top.",

  /* ── Dialog & kartu kecil dashboard ─────────────────────────────────────── */
  "1 bulan": "1 month",
  "30 menit": "30 minutes",
  "45 menit": "45 minutes",
  "Ada yang error atau aneh? Ceritain di sini — laporannya langsung masuk ke tim Linguo.": "Something broken or odd? Tell us here — the report goes straight to the Linguo team.",
  "Akses": "Access",
  "Akses gratis dibatasi sesuai ketentuan kode promo.": "Free access is limited by the promo code terms.",
  "Akses terbuka di": "Access opens at",
  "Angka di bawah = nomor pertemuan. Batang yang ada pembahasannya bisa diklik.": "The numbers below are meeting numbers. Bars with explanations are clickable.",
  "Atau coba dulu": "Or try",
  "Audio": "Audio",
  "Bacaan, gloss, contoh kalimat": "Reading, glosses, example sentences",
  "Bahasa Kamu": "Your Languages",
  "Belum ada materi mandiri kamu": "No self-study material yet",
  "Belum ada nilai kuis": "No quiz scores yet",
  "Belum ada yang dikuasai — review": "Nothing mastered yet — review",
  "Belum tepat": "Not quite",
  "Biasanya 1–2 jam di jam kerja (08:00–17:00 WIB)": "Usually 1–2 hours during work hours (08:00–17:00 WIB)",
  "Booking Sesi": "Book a Session",
  "Buat kelas live, rekaman & materi sesi nyata ada di tab": "For live classes, the real recordings & session materials live in the",
  "Buka Zoom": "Open Zoom",
  "Buka akses penuh": "Unlock full access",
  "Buka panel Bahasa Kamu": "Open the Your Languages panel",
  "Bukti ditolak": "Proof rejected",
  "Bukti sudah diupload": "Proof uploaded",
  "Bukti terkirim — menunggu verifikasi": "Proof sent — awaiting verification",
  "Catatan buat kamu": "Notes for you",
  "Ceritain detailnya": "Tell us the details",
  "Chapter": "Chapter",
  "Checkout": "Checkout",
  "Contoh: Tombol mulai simulasi gak bisa diklik": "e.g. The start simulation button won't click",
  "Deskripsi bahasa": "Language description",
  "Di mode pratinjau, kata tersimpan mengikuti perangkat ini — bukan milik siswanya.": "In preview mode, saved words follow this device — they are not the student's.",
  "Dihitung dari materi & kuis yang sudah kamu selesaikan": "Counted from the materials & quizzes you finished",
  "File harus berupa gambar (JPG/PNG/WebP).": "The file must be an image (JPG/PNG/WebP).",
  "File materi": "Material files",
  "Foto / Video": "Photo / Video",
  "Gagal mengirim laporan": "Couldn't send the report",
  "Gambar dari tab lain ga bisa diambil (kemungkinan diblokir situsnya). Coba simpan dulu lalu drag filenya.": "An image from another tab can't be grabbed (the site probably blocks it). Save it first, then drag the file.",
  "Gambar maks": "Images up to",
  "Gratis A1 · A2–B2 terkunci": "A1 free · A2–B2 locked",
  "Instruksi Pembayaran": "Payment Instructions",
  "Jadwal Tetap": "Fixed Schedule",
  "Jadwal batch akan segera diinfokan admin via WhatsApp": "The admin will share the batch schedule on WhatsApp soon",
  "Jadwal belum ditentukan": "Not scheduled yet",
  "Kamu belum punya paket Belajar Mandiri. Daftar dulu bahasanya biar materinya muncul di sini.": "You don't have a Self-Study package yet. Enroll in a language and its material will show up here.",
  "Kamu lagi pakai versi gratis (level A1). Buka": "You're on the free version (level A1). Unlock",
  "Kamu perlu login dulu untuk pakai kode promo.": "You need to sign in first to use a promo code.",
  "Kelas berikutnya": "Next class",
  "Kelas disesuaikan untuk anak usia 5–12 tahun": "Class tailored for children aged 5–12",
  "Kirim Laporan": "Send Report",
  "Klaim Akses Gratis": "Claim Free Access",
  "Klik atau drag gambar untuk ganti foto": "Click or drag an image to change the photo",
  "Klik upload lagi untuk mengganti": "Upload again to replace it",
  "Kode": "Code",
  "Kode Promo / Afiliator": "Promo / Affiliate Code",
  "Koreksi per soal": "Question-by-question review",
  "Kosakata Saya masih kosong": "My Vocabulary is still empty",
  "Lagi buka menu apa, ngeklik apa, terus yang muncul apa. Makin detail makin cepat kami perbaiki.": "Which menu you were on, what you clicked, and what happened. The more detail, the faster we fix it.",
  "Laporan terkirim — makasih! Tim Linguo bakal cek ya 🐛": "Report sent — thank you! The Linguo team will look into it 🐛",
  "Latihan & kuis": "Practice & quiz",
  "Latihan flashcard": "Flashcard practice",
  "Level A1 gratis buat dicoba. Lanjut ke A2–B2 dengan akses penuh — sekali bayar, bukan langganan kartu otomatis.": "Level A1 is free to try. Continue to A2–B2 with full access — a one-time payment, not an auto-renewing subscription.",
  "Level Progress": "Level Progress",
  "Level di bahasa ini": "Levels in this language",
  "Level kamu": "Your level",
  "Lihat Detail Kelas": "View Class Details",
  "Lihat di halaman silabus": "See it on the syllabus page",
  "Lihat kartu dengan badge 'Belum Bayar'": "Check the card with the 'Unpaid' badge",
  "Lihat kartu dengan badge kuning / merah": "Check the cards with a yellow / red badge",
  "Link Google Drive / Zoom recording": "Google Drive / Zoom recording link",
  "Lipat panel Bahasa Kamu": "Collapse the Your Languages panel",
  "Masalahnya apa?": "What's the problem?",
  "Masih dalam pengembangan — segera hadir.": "Still in development — coming soon.",
  "Masih kurang": "Needs work",
  "Masukkan kode": "Enter a code",
  "Materi & kosakata": "Material & vocabulary",
  "Materi interaktif sesi ini": "This session's interactive material",
  "Materi sedang disiapkan": "Material is being prepared",
  "Memproses...": "Processing...",
  "Memuat materi…": "Loading materials…",
  "Memuat pembahasan…": "Loading the explanations…",
  "Mengaktifkan...": "Activating...",
  "Menunggu verifikasi admin": "Awaiting admin verification",
  "Mulai belajar": "Start learning",
  "Naik": "Up",
  "Nama": "Name",
  "Nilai": "Score",
  "Nilai Kuis per Pertemuan": "Quiz Score per Meeting",
  "Nilai kuis tiap pertemuan muncul di sini setelah pengajar mengisinya": "Each meeting's quiz score shows up here once your teacher fills it in",
  "PDF / slide — berupa link": "PDF / slides — as a link",
  "Pelajaran interaktif buat sesi ini lagi disiapin — pantau terus, ya.": "The interactive lesson for this session is being prepared — stay tuned.",
  "Pelajaran interaktif tersedia": "Interactive lesson available",
  "Pembahasan belum tersedia untuk kuis ini.": "No explanation is available for this quiz yet.",
  "Pembayaran aman via Xendit: QRIS, GoPay, OVO, Dana, ShopeePay, Transfer Bank": "Secure payment via Xendit: QRIS, GoPay, OVO, Dana, ShopeePay, bank transfer",
  "Perbaikannya": "How to improve",
  "Periode": "Period",
  "Pilih Paket": "Pick a Package",
  "Pilih foto atau video — boleh beberapa sekaligus": "Pick photos or videos — several at once is fine",
  "Pilih paket": "Choose this plan",
  "Pilihan ganda + isian rumpang": "Multiple choice + fill in the blanks",
  "Placement Test": "Placement Test",
  "Rekaman / video sesi": "Session recording / video",
  "Rekaman sesi": "Session recording",
  "Riwayat sesi, materi & rekaman akan tampil di sini": "Session history, materials & recordings will appear here",
  "Salin": "Copy",
  "Seberapa mengganggu?": "How disruptive is it?",
  "Selamanya · kapan aja": "Forever · anytime",
  "Sesi diatur admin": "Sessions arranged by the admin",
  "Sesi kamu habis — coba login ulang dulu ya": "Your session expired — please sign in again",
  "Setelah transfer, upload bukti di bawah — atau kirim via WhatsApp.": "After transferring, upload the proof below — or send it via WhatsApp.",
  "Silabus belum tersedia untuk bahasa ini": "No syllabus available for this language yet",
  "Silabus lengkap": "Full syllabus",
  "Silakan upload ulang bukti yang benar.": "Please upload the correct proof again.",
  "Simpan kata sambil nonton di Watch & Learn, atau selesaikan materi kelas — hitungannya muncul di sini.": "Save words while watching in Watch & Learn, or finish your class material — the count shows up here.",
  "Slide berikutnya": "Next slide",
  "Slide sebelumnya": "Previous slide",
  "Sudah bagus": "Doing well",
  "Tanggal sesi tak tercatat di aplikasi": "The session date is not recorded in the app",
  "Target": "Target",
  "Target level": "Target level",
  "Tentang bahasa ini": "About this language",
  "Tidak ada bahasa di filter ini": "No language matches this filter",
  "Tonton rekaman": "Watch the recording",
  "Total Transfer": "Total to transfer",
  "Transfer persis sesuai nominal": "Transfer the exact amount",
  "Turun": "Down",
  "Ukuran gambar maksimal 5MB.": "Images can be at most 5MB.",
  "Ulang lagi": "Revisit",
  "Upload gagal. Coba lagi atau pakai file lain.": "Upload failed. Try again or use another file.",
  "Video pelajaran": "Lesson video",
  "a.n.": "a/n",
  "agar mudah diverifikasi.": "so it is easy to verify.",
  "akses selamanya": "lifetime access",
  "bagian sesuai format tes asli": "sections matching the real test format",
  "bahasa · belajar mandiri": "languages · self-study",
  "belum dinilai": "not graded yet",
  "buat lanjut sampai mahir.": "to keep going all the way to advanced.",
  "bulan": "month",
  "chapter": "chapters",
  "dari penilaian sebelumnya": "from the previous assessment",
  "dipakai untuk akses": "used for access",
  "gratis, tanpa bayar!": "free, no payment!",
  "hal perlu perhatian": "things need your attention",
  "kata": "words",
  "kata biar naik status": "words to move them up",
  "kata dikuasai": "words mastered",
  "kata lagi dipelajari — tinggal": "words still being learned —",
  "kata lagi menuju target level": "more words to reach level",
  "kata menuju target.": "words to go to the target.",
  "kata tersimpan di Watch & Learn": "words saved in Watch & Learn",
  "klik untuk lihat pembahasan": "click to see the explanation",
  "kuis": "quizzes",
  "kursus aktif": "active courses",
  "lampiran": "attachments",
  "minggu": "weeks",
  "mnt/sesi": "min/session",
  "opsional": "optional",
  "opsional, tapi sangat membantu": "optional, but it helps a lot",
  "rekaman": "recordings",
  "sesi lagi disiapkan": "more sessions being prepared",
  "sesi persiapan": "prep sessions",
  "soal kuis": "quiz questions",
  "tetap": "unchanged",
  "video maks": "videos up to",
  "Sesuai format tes asli TOEFL & IELTS": "Matches the real TOEFL & IELTS format",
  "Skor & pembahasan langsung keluar": "Score & explanations right away",
  "Akses selamanya (sekali bayar)": "Lifetime access (one-time payment)",
  "Akses semua level dari A2 sampai B2": "Access every level from A2 through B2",
  "Audio pelafalan native + kuis di tiap sesi": "Native pronunciation audio + a quiz in every session",
  "Materi bisa diakses kapan aja selama masa aktif": "Material available anytime while your access lasts",
  "Belajar terstruktur dengan urutan ala kelas": "Structured learning that follows a real class order",
  "Parah — sama sekali gak bisa dipakai": "Critical — completely unusable",
  "Tinggi — fitur penting rusak": "High — an important feature is broken",
  "Sedang — ganggu tapi masih bisa jalan": "Medium — annoying but still workable",
  "Ringan — tampilan / typo": "Low — visual glitch / typo",
  "Mendatang": "Upcoming",

  /* ── Pemutar Watch & Learn (transkrip, analisa kata/kalimat, kuis) ──────── */
  "20 dtk/soal": "20 sec/question",
  "Analisa Kalimat": "Sentence Analysis",
  "Analisa grammar kalimat": "Analyze sentence grammar",
  "Analisa kalimat": "Sentence analysis",
  "Analisa kalimat ini dengan AI": "Analyze this sentence with AI",
  "Analisa kalimat tayang (AI)": "Analyze the current sentence (AI)",
  "Apa artinya?": "What does it mean?",
  "Arti kata & Analisa grammar tanpa batas di semua video. Nonton + subtitle + terjemahan tetap gratis.": "Unlimited word meanings & grammar analysis on every video. Watching + subtitles + translation stay free.",
  "Atau tulis pertanyaanmu sendiri…": "Or write your own question…",
  "Atur lebar panel analisa": "Resize the analysis panel",
  "Atur lebar transkrip": "Resize the transcript",
  "Bahasa target (yang mau dipelajari)": "Target language (the one you are learning)",
  "Bahasa yang dipelajari": "Language you are learning",
  "Batal auto-play": "Cancel autoplay",
  "Belajar bareng guru": "Learn with a teacher",
  "Belum bisa main": "Can't play yet",
  "Bentuk": "Form",
  "Bonus streak": "Streak bonus",
  "Buka analisa kata ini": "Open the analysis for this word",
  "Buka semua fitur belajar": "Unlock every learning feature",
  "Coba kelas trial gratis — ngobrol langsung sama pengajar.": "Try a free trial class — talk with a teacher directly.",
  "Coba tutup lalu buka lagi kalimat ini.": "Try closing and reopening this sentence.",
  "Coba tutup lalu buka lagi kata ini.": "Try closing and reopening this word.",
  "Contoh Kalimat": "Example Sentences",
  "Dengar contoh": "Hear the example",
  "Dengar kata": "Hear the word",
  "Dijeda": "Paused",
  "Email (untuk invoice & aktivasi)": "Email (for the invoice & activation)",
  "Frasa": "Phrase",
  "Gagal cek status pembayaran.": "Couldn't check the payment status.",
  "Gagal membuat invoice.": "Couldn't create the invoice.",
  "Gagal memeriksa kode. Coba lagi.": "Couldn't check the code. Try again.",
  "Gagal memuat analisa": "Couldn't load the analysis",
  "Gagal memuat jawaban. Coba lagi.": "Couldn't load the answer. Try again.",
  "Gagal memuat materi": "Couldn't load the material",
  "Gagal memulai pembuatan subtitle AI (bisa jadi sesaat). Subtitle bawaan YouTube (CC) sudah dinyalakan — coba lagi ya.": "Couldn't start AI subtitle generation (possibly temporary). YouTube's built-in captions (CC) are on — please try again.",
  "Gagal menganalisa — ketuk untuk coba lagi": "Analysis failed — tap to try again",
  "Gagal menyimpan — penyimpanan browser penuh. Bersihkan data situs lalu coba lagi.": "Couldn't save — browser storage is full. Clear the site data and try again.",
  "Gagal menyimpan — penyimpanan browser penuh. Coba tutup tab lain atau bersihkan data situs, lalu simpan lagi.": "Couldn't save — browser storage is full. Close other tabs or clear the site data, then save again.",
  "Geser posisi subtitle (klik-ganda untuk reset)": "Move the subtitle (double-click to reset)",
  "Geser posisi video": "Seek the video",
  "Harfiah": "Literal",
  "Hasil Kuis": "Quiz Result",
  "Idiom": "Idiom",
  "Idiom & Ungkapan": "Idioms & Expressions",
  "Invoice tidak tersedia. Coba lagi.": "The invoice is unavailable. Try again.",
  "Jeda": "Pause",
  "Kamu kuasai": "You nailed",
  "Kamu sudah pakai": "You've used all",
  "Kapan & Bagaimana Dipakai": "When & How It Is Used",
  "Kata Mirip yang Gampang Ketuker": "Similar Words People Mix Up",
  "Kecepatan": "Speed",
  "Kecilkan video & tampilkan rekomendasi": "Shrink the video & show recommendations",
  "Keluar kuis": "Leave the quiz",
  "Kembali (kecilkan video)": "Back (shrink the video)",
  "Kembalikan": "Restore",
  "Kembalikan ukuran video": "Restore the video size",
  "Kenapa begitu": "Why",
  "Keren —": "Nice —",
  "Kirim pertanyaan": "Send question",
  "Kode promo / afiliator": "Promo / affiliate code",
  "Kode promo tidak berlaku.": "That promo code is not valid.",
  "Konjugasi": "Conjugation",
  "Kosakata tersimpan dari video ini": "Words saved from this video",
  "Kosongkan riwayat": "Clear history",
  "Kualitas video (hemat paket data)": "Video quality (save data)",
  "Kuis Arti Kata": "Meaning Quiz",
  "Kuis butuh minimal": "The quiz needs at least",
  "Kuota pembuatan subtitle AI hari ini sudah penuh — coba lagi besok ya. Sementara itu subtitle bawaan YouTube (CC) sudah dinyalakan supaya kamu tetap bisa belajar.": "Today's AI subtitle quota is full — try again tomorrow. In the meantime YouTube's built-in captions (CC) are on so you can keep learning.",
  "Lainnya untukmu": "More for you",
  "Langganan": "Subscribe",
  "Langganan aktif! Arti kata & Analisa terbuka penuh 🎉": "Subscription active! Word meanings & Analysis are fully unlocked 🎉",
  "Lanjut menonton": "Keep watching",
  /* [watch-lanjut-menit-v1] "Lanjut dari 7:12" — jamnya dirakit di komponen. */
  "Lanjut dari": "Resume at",
  /* [lingbook-sampul-kartu-v1] "Halaman 12/135" di kartu Lingbook. */
  "Halaman": "Page",
  "Maaf, tidak ada jawaban. Coba lagi.": "Sorry, no answer came back. Try again.",
  "Main lagi": "Play again",
  "Masukkan email yang valid untuk kirim invoice & aktivasi.": "Enter a valid email so we can send the invoice & activate access.",
  "Matikan analisa grammar": "Turn off grammar analysis",
  "Membuat subtitle dengan AI… (~1 menit)": "Generating subtitles with AI… (~1 minute)",
  "Membuat subtitle dengan AI… ini bisa memakan waktu sekitar 1 menit. Kamu bisa tetap menonton dulu.": "Generating subtitles with AI… this can take about a minute. Feel free to keep watching.",
  "Memuat transkrip…": "Loading the transcript…",
  "Mencari arti…": "Looking up the meaning…",
  "Menerjemahkan…": "Translating…",
  "Menonton dengan subtitle bawaan YouTube.": "Watching with YouTube's built-in captions.",
  "Menyiapkan bacaan Latin…": "Preparing the romanization…",
  "Menyiapkan pembayaran…": "Preparing the payment…",
  "Menyiapkan subtitle…": "Preparing subtitles…",
  "Nanti aja, lanjut nonton": "Maybe later, keep watching",
  "Opsi subtitle & terjemahan": "Subtitle & translation options",
  "Pecahan Kalimat": "Sentence Breakdown",
  "Pembayaran belum terkonfirmasi. Cek email invoice-mu.": "The payment is not confirmed yet. Check your invoice email.",
  "Pembayaran dibatalkan. Coba lagi kapan saja.": "Payment cancelled. You can try again anytime.",
  "Pembuatan transkrip sempat gagal (bisa jadi sesaat). Subtitle bawaan YouTube (CC) sudah dinyalakan — kamu bisa coba siapkan transkrip interaktif lagi.": "Building the transcript failed (possibly temporary). YouTube's built-in captions (CC) are on — you can try preparing the interactive transcript again.",
  "Perlu diulang": "Needs another round",
  "Punya kode promo / afiliator?": "Have a promo / affiliate code?",
  "Putar": "Play",
  "Putar dalam": "Playing in",
  "Sehari-hari": "Everyday",
  "Selesai ditonton": "Finished watching",
  "Sembunyikan CC": "Hide CC",
  "Sembunyikan terjemahan": "Hide the translation",
  "Sembunyikan transkrip": "Hide the transcript",
  "Seret untuk atur lebar · klik ganda untuk reset": "Drag to resize · double-click to reset",
  "Seret untuk memindahkan subtitle • klik-ganda untuk reset": "Drag to move the subtitle • double-click to reset",
  "Simpan lebih banyak kata saat menonton Watch & Learn, lalu balik ke sini.": "Save more words while watching Watch & Learn, then come back here.",
  "Simulasi TOEFL/IELTS — tahu posisimu sekarang.": "A TOEFL/IELTS simulation — see where you stand right now.",
  "Skor kamu": "Your score",
  "Streak": "Streak",
  "Struktur & Tata Bahasa": "Structure & Grammar",
  "Subtitle": "Subtitles",
  "Subtitle AI-nya masih diproses lebih lama dari biasanya. Subtitle bawaan YouTube (CC) sudah dinyalakan — coba muat ulang sebentar lagi.": "The AI subtitles are taking longer than usual. YouTube's built-in captions (CC) are on — try reloading in a moment.",
  "Suffix": "Suffix",
  "Tagih bulanan": "Billed monthly",
  "Tampilkan CC": "Show CC",
  "Tampilkan terjemahan": "Show the translation",
  "Tampilkan transkrip": "Show the transcript",
  "Tanya AI": "Ask AI",
  "Tanya apa saja tentang": "Ask anything about",
  "Tanya apa saja tentang kalimat ini…": "Ask anything about this sentence…",
  "Tebak arti tiap kata sebelum waktu habis. Makin cepat & makin beruntun, makin besar poinmu.": "Guess each word before time runs out. The faster and the longer your streak, the more points you score.",
  "Terapkan": "Apply",
  "Terjadi kesalahan. Coba lagi.": "Something went wrong. Try again.",
  "Terjemahan": "Translation",
  "Tersimpan": "Saved",
  "Tidak ada arti mandiri — mungkin kata fungsi tata bahasa.": "No standalone meaning — it is probably a grammatical function word.",
  "Tonton berikutnya": "Watch next",
  "Tonton lagi": "Watch again",
  "Transkrip": "Transcript",
  "Transkrip interaktif belum bisa disiapkan untuk video ini. Subtitle bawaan YouTube (CC) sudah dinyalakan supaya kamu tetap bisa belajar sambil menonton.": "An interactive transcript can't be prepared for this video yet. YouTube's built-in captions (CC) are on so you can still learn while watching.",
  "Tutup player": "Close the player",
  "Tutup riwayat": "Close history",
  "Ukur levelmu": "Measure your level",
  "Ukuran teks subtitle": "Subtitle text size",
  "Video lainnya — tetap di Watch & Learn": "More videos — stay in Watch & Learn",
  "bln": "mo",
  "hemat": "save",
  "kata gratis. Kamu jelas serius belajar — ini langkah paling ampuh biar cepat bisa:": "free words. You're clearly serious about learning — here's the fastest way forward:",
  "kata tersimpan!": "words saved!",
  "siap": "ready",
  "video siap tonton": "videos ready to watch",
  "yang punya arti. Kamu punya": "words with meanings. You have",
  "Warna = kelas kata": "Colour = part of speech",
  "benda": "noun",
  "kerja": "verb",
  "sifat": "adjective",
  "keterangan": "adverb",
  "ganti": "pronoun",
  "depan": "preposition",
  "sambung": "conjunction",
  "sandang": "determiner",
  "bilangan": "numeral",
  "seru": "interjection",
  "partikel": "particle",
  "bantu": "auxiliary",
  "tanda baca": "punctuation",
  "lainnya": "other",
  "Formal": "Formal",
  "Netral": "Neutral",
  "Santai": "Casual",
  "Sopan": "Polite",
  "Kasar": "Rude",
  "Kapan kata ini dipakai?": "When is this word used?",
  "Apa bedanya dengan kata yang mirip?": "How is it different from similar words?",
  "Beri contoh dalam situasi formal": "Give an example in a formal situation",
  "Beri contoh dalam situasi santai": "Give an example in a casual situation",
  "Jelaskan tata bahasanya lebih dalam": "Explain the grammar in more depth",
  "Kenapa urutan katanya begini?": "Why is the word order like this?",
  "Buat contoh kalimat yang mirip": "Make a similar example sentence",
  "Podcast": "Podcast",
  "Wawancara": "Interviews",
  "Memasak": "Cooking",
  "Komedi": "Comedy",
  "Kecil": "Small",
  "Sedang": "Medium",
  "Besar": "Large",
};
