import { copyFileSync } from 'fs';
copyFileSync('BlogContent.tsx', 'src/app/blog/BlogContent.tsx');
console.log('✅ Blog dual view installed!');
console.log('');
console.log('🔄 Feed view (Medium-style):');
console.log('   • Infinite scroll — auto-load saat scroll ke bawah');
console.log('   • Article list: title + excerpt + thumbnail kanan');
console.log('   • Author line + read time + date');
console.log('   • Sidebar: Staff Picks + Recommended Topics + Bahasa links');
console.log('');
console.log('📱 Grid view (Figma-style):');
console.log('   • Promo banner CTA');
console.log('   • 3-column card grid + pagination');
console.log('   • Terbaru / Populer / Direkomendasikan sections');
console.log('');
console.log('🔀 Toggle: icon buttons di navbar (List / Grid)');
console.log('');
console.log('Run: git add -A && git commit -m "feat: dual view blog (feed + grid)" && git push');
