// linguo-patch:kelas-lucide-icons-v1 — ikon whyLearn & persona di /kursus/bahasa-*
// dirender pakai Lucide (bukan emoji). Data languages-detail.ts tetap menyimpan
// emoji sebagai KUNCI — komponen ini yang menerjemahkannya ke ikon. Emoji yang
// belum terpetakan jatuh ke Sparkles, jadi nambah entri data baru tidak pernah
// mematikan halaman.
import {
  Anchor, ArrowRight, Baby, Bath, Beer, Bird, BookOpen, Brain, Briefcase,
  Building, Building2, Car, Castle, Check, ChefHat, Clapperboard,
  ClipboardList, Construction, Croissant, Cross, Factory, Fish, Flag, Flame,
  Flower, Flower2, Fuel, Gem, Globe, GraduationCap, Handshake, Heart,
  HeartPulse, Hotel, House, Landmark, Laptop, Library, Luggage, Map,
  MessageCircle, Mic, Microscope, MoonStar, Mountain, Music, Newspaper,
  Package, Palette, PenLine, Pill, Plane, Puzzle, RefreshCw, Sailboat,
  Satellite, Scale, School, Scroll, Ship, ShoppingBag, Sparkles, Stamp, Star,
  Stethoscope, Swords, TreePalm, TreePine, TrendingUp, TrainFront, Trophy, Tv,
  Users, UtensilsCrossed, VenetianMask, Wallet, Wine, Zap,
  type LucideIcon,
} from "lucide-react";

const ICON_BY_EMOJI: Record<string, LucideIcon> = {
  "⚓": Anchor,
  "⚔️": Swords,
  "⚖️": Scale,
  "⚡": Zap,
  "⚽": Trophy,
  "⛵": Sailboat,
  "✈️": Plane,
  "✍️": PenLine,
  "✝️": Cross,
  "❤️": Heart,
  "⭐": Star,
  "🀄": Users,
  "🇪🇺": Flag,
  "🇹🇱": Flag,
  "🌆": Building2,
  "🌋": Mountain,
  "🌍": Globe,
  "🌎": Globe,
  "🌏": Globe,
  "🌐": Globe,
  "🌲": TreePine,
  "🌹": Flower,
  "🌺": Flower,
  "🌻": Flower2,
  "🍝": UtensilsCrossed,
  "🍷": Wine,
  "🍺": Beer,
  "🎌": Flag,
  "🎓": GraduationCap,
  "🎙️": Mic,
  "🎣": Fish,
  "🎤": Mic,
  "🎨": Palette,
  "🎬": Clapperboard,
  "🎭": VenetianMask,
  "🎵": Music,
  "🎶": Music,
  "🏔️": Mountain,
  "🏗️": Construction,
  "🏙️": Building2,
  "🏛️": Landmark,
  "🏝️": TreePalm,
  "🏠": House,
  "🏡": House,
  "🏢": Building,
  "🏥": HeartPulse,
  "🏨": Hotel,
  "🏫": School,
  "🏭": Factory,
  "🏰": Castle,
  "👨‍🍳": ChefHat,
  "👶": Baby,
  "💊": Pill,
  "💍": Gem,
  "💰": Wallet,
  "💹": TrendingUp,
  "💻": Laptop,
  "💼": Briefcase,
  "📈": TrendingUp,
  "📋": ClipboardList,
  "📖": BookOpen,
  "📚": Library,
  "📜": Scroll,
  "📡": Satellite,
  "📦": Package,
  "📰": Newspaper,
  "📺": Tv,
  "📿": Sparkles,
  "🔁": RefreshCw,
  "🔄": RefreshCw,
  "🔬": Microscope,
  "🕉️": Flower2,
  "🕊️": Bird,
  "🕋": Landmark,
  "🕌": MoonStar,
  "🕎": Flame,
  "🗣️": MessageCircle,
  "🗺️": Map,
  "🚄": TrainFront,
  "🚗": Car,
  "🚢": Ship,
  "🛁": Bath,
  "🛂": Stamp,
  "🛍️": ShoppingBag,
  "🛕": Landmark,
  "🛢️": Fuel,
  "🛶": Sailboat,
  "🤝": Handshake,
  "🥐": Croissant,
  "🧑‍⚕️": Stethoscope,
  "🧗": Mountain,
  "🧘": Flower2,
  "🧛": Castle,
  "🧠": Brain,
  "🧩": Puzzle,
  "🧳": Luggage,
  "🩺": Stethoscope,
};

export function DetailIcon({
  emoji,
  className = "h-7 w-7",
}: {
  emoji: string;
  className?: string;
}) {
  const Icon = ICON_BY_EMOJI[emoji.trim()] ?? Sparkles;
  return <Icon aria-hidden className={className} strokeWidth={1.75} />;
}

export { ArrowRight, Check };
