// [placement-bank-acak-v1] Stok tambahan bank soal placement test Bahasa Inggris.
// Tiap soal tetap di src/data/placement/english.ts (q1…q18, l1…l5) punya 3 varian
// setara di sini (akhiran b/c/d): level sama, tipe sama, listening tetap listening.
// Bentuk objeknya = tipe Question di english.ts. Masuk ke tabel
// placement_question_bank lewat scripts/placement-bank/seed.mjs.

export const englishBankTambahan = [
  // ═══════════════════════ A1 ═══════════════════════
  {
    id: "q1b", difficulty: "A1", type: "multiple",
    question: "Which word is a day of the week?",
    options: ["January", "Monday", "Summer", "Morning"],
    correct: 1,
    explanation: "'Monday' = Senin. 'January' nama bulan, 'summer' musim, 'morning' waktu dalam sehari.",
  },
  {
    id: "q1c", difficulty: "A1", type: "multiple",
    question: "Choose the correct sentence.",
    options: ["She are a student.", "She is a student.", "She am a student.", "She be a student."],
    correct: 1,
    explanation: "He/she/it memakai 'is'. 'Am' hanya untuk 'I', 'are' untuk you/we/they.",
  },
  {
    id: "q1d", difficulty: "A1", type: "multiple",
    question: "A: 'How are you?' — B: '___'",
    options: ["I'm fine, thank you.", "I'm twenty years old.", "I'm from Indonesia.", "I'm a teacher."],
    correct: 0,
    explanation: "'How are you?' menanyakan kabar. Umur dijawab untuk 'How old are you?', asal untuk 'Where are you from?', pekerjaan untuk 'What do you do?'.",
  },
  {
    id: "q2b", difficulty: "A1", type: "matching",
    prompt: "Match the family words with their Indonesian meanings:",
    pairs: [
      { left: "mother", right: "ibu" },
      { left: "brother", right: "saudara laki-laki" },
      { left: "daughter", right: "anak perempuan" },
      { left: "husband", right: "suami" },
    ],
    explanation: "Kosakata keluarga dasar level A1. 'Daughter' = anak perempuan (lawannya 'son'), 'husband' = suami (lawannya 'wife').",
  },
  {
    id: "q2c", difficulty: "A1", type: "matching",
    prompt: "Match the words with their Indonesian meanings:",
    pairs: [
      { left: "bread", right: "roti" },
      { left: "rice", right: "nasi" },
      { left: "water", right: "air" },
      { left: "egg", right: "telur" },
    ],
    explanation: "Kosakata makanan dan minuman dasar level A1 — dipakai setiap hari saat memesan atau berbelanja.",
  },
  {
    id: "q2d", difficulty: "A1", type: "matching",
    prompt: "Match the adjectives with their Indonesian meanings:",
    pairs: [
      { left: "big", right: "besar" },
      { left: "cold", right: "dingin" },
      { left: "new", right: "baru" },
      { left: "cheap", right: "murah" },
    ],
    explanation: "Kata sifat dasar level A1. Lawan katanya: big–small, cold–hot, new–old, cheap–expensive.",
  },
  {
    id: "q3b", difficulty: "A1", type: "fillChoice",
    question: "Complete: 'They ___ from Japan.'",
    context: "Pilih bentuk 'to be' yang tepat.",
    options: ["is", "am", "are", "be"],
    correct: "are",
    explanation: "'They' (juga you dan we) memakai 'are'.",
  },
  {
    id: "q3c", difficulty: "A1", type: "fillChoice",
    question: "Complete: 'The book is ___ the table.'",
    context: "Pilih preposisi yang tepat.",
    options: ["on", "to", "of", "for"],
    correct: "on",
    explanation: "'On' = di atas (menempel pada permukaan). 'On the table' = di atas meja.",
  },
  {
    id: "q3d", difficulty: "A1", type: "fillChoice",
    question: "Complete: 'This is my sister. ___ name is Anna.'",
    context: "Pilih kata ganti milik yang tepat.",
    options: ["His", "Her", "She", "Their"],
    correct: "Her",
    explanation: "'Her' = milik dia (perempuan). 'His' untuk laki-laki, 'she' kata ganti subjek (bukan milik), 'their' milik mereka.",
  },
  {
    id: "q4b", difficulty: "A1", type: "dragDrop",
    prompt: "Susun menjadi kalimat lengkap:",
    translation: "Saya punya dua kucing.",
    tokens: ["two", "I", "cats", "have"],
    correct: ["I", "have", "two", "cats"],
    explanation: "Struktur dasar: Subject + have + jumlah + noun jamak (cats).",
  },
  {
    id: "q4c", difficulty: "A1", type: "dragDrop",
    prompt: "Susun menjadi kalimat lengkap:",
    translation: "Dia (laki-laki) berasal dari Indonesia.",
    tokens: ["from", "He", "Indonesia", "is"],
    correct: ["He", "is", "from", "Indonesia"],
    explanation: "Menyebut asal: Subject + be (is/am/are) + from + tempat.",
  },
  {
    id: "q4d", difficulty: "A1", type: "dragDrop",
    prompt: "Susun menjadi kalimat lengkap:",
    translation: "Kami tinggal di Jakarta.",
    tokens: ["in", "We", "Jakarta", "live"],
    correct: ["We", "live", "in", "Jakarta"],
    explanation: "Struktur dasar: Subject + verb + in + nama kota.",
  },
  {
    id: "l1b", difficulty: "A1", type: "fillChoice",
    audio: { lang: "en", text: "Hello, I'm Tom. I get up at six o'clock every day. I have breakfast with my sister, and then I walk to school." },
    question: "Dengarkan audio, lalu lengkapi: 'I get up at ___ o'clock every day.'",
    context: "Pilih kata yang kamu dengar.",
    options: ["six", "sixteen", "seven", "sixty"],
    correct: "six",
    explanation: "Transkrip: 'Hello, I'm Tom. I get up at six o'clock every day. I have breakfast with my sister, and then I walk to school.' (Halo, saya Tom. Saya bangun jam enam setiap hari. Saya sarapan bersama adik perempuan saya, lalu berjalan kaki ke sekolah.) Awas angka yang bunyinya mirip: 'six' = 6, 'sixteen' = 16 (tekanan di '-teen'), 'sixty' = 60.",
  },
  {
    id: "l1c", difficulty: "A1", type: "fillChoice",
    audio: { lang: "en", text: "This is my room. There is a small bed, a desk, and a blue chair. My cat likes to sleep on the bed." },
    question: "Dengarkan audio, lalu lengkapi: 'There is a small bed, a desk, and a blue ___.'",
    context: "Pilih kata yang kamu dengar.",
    options: ["chair", "hair", "cheer", "share"],
    correct: "chair",
    explanation: "Transkrip: 'This is my room. There is a small bed, a desk, and a blue chair. My cat likes to sleep on the bed.' (Ini kamar saya. Ada tempat tidur kecil, meja, dan kursi biru. Kucing saya suka tidur di atas tempat tidur.) 'Chair' /tʃeə/ = kursi. 'Hair' = rambut, 'cheer' = sorakan, 'share' = berbagi — bunyinya mirip tapi tidak cocok untuk perabot kamar.",
  },
  {
    id: "l1d", difficulty: "A1", type: "fillChoice",
    audio: { lang: "en", text: "Excuse me, how much is this bag? It's fifteen dollars. Great, I'll take it. Thank you!" },
    question: "Dengarkan audio, lalu lengkapi: 'It's ___ dollars.'",
    context: "Pilih kata yang kamu dengar.",
    options: ["fifty", "fifteen", "five", "fourteen"],
    correct: "fifteen",
    explanation: "Transkrip: 'Excuse me, how much is this bag? It's fifteen dollars. Great, I'll take it. Thank you!' (Permisi, berapa harga tas ini? Lima belas dolar. Bagus, saya ambil. Terima kasih!) 'Fifteen' = 15, tekanannya di '-teen'. 'Fifty' = 50, tekanannya di awal kata — pasangan angka ini paling sering tertukar.",
  },

  // ═══════════════════════ A2 ═══════════════════════
  {
    id: "q5b", difficulty: "A2", type: "multiple",
    question: "Which sentence talks about a future plan?",
    options: [
      "I am going to visit my grandmother next week.",
      "I visited my grandmother last week.",
      "I visit my grandmother every week.",
      "I have visited my grandmother twice.",
    ],
    correct: 0,
    explanation: "'Be going to + verb' dipakai untuk rencana yang sudah diputuskan. Kalimat lain: past simple, present simple (rutinitas), dan present perfect (pengalaman).",
  },
  {
    id: "q5c", difficulty: "A2", type: "multiple",
    question: "Choose the correct comparative: 'This phone is ___ than my old one.'",
    options: ["more good", "better", "gooder", "best"],
    correct: 1,
    explanation: "'Good' punya bentuk perbandingan tak beraturan: good → better → best. 'Best' adalah superlatif, tidak dipakai bersama 'than'.",
  },
  {
    id: "q5d", difficulty: "A2", type: "multiple",
    question: "Which question is correct?",
    options: [
      "Where you did go yesterday?",
      "Where did you went yesterday?",
      "Where did you go yesterday?",
      "Where you went yesterday?",
    ],
    correct: 2,
    explanation: "Kalimat tanya past simple: kata tanya + did + subject + verb bentuk dasar. Setelah 'did', verb kembali ke bentuk dasar ('go', bukan 'went').",
  },
  {
    id: "q6b", difficulty: "A2", type: "dragDrop",
    prompt: "Susun menjadi kalimat present continuous:",
    translation: "Dia (perempuan) sedang memasak makan malam sekarang.",
    tokens: ["cooking", "She", "now", "is", "dinner"],
    correct: ["She", "is", "cooking", "dinner", "now"],
    explanation: "Present continuous: Subject + is/am/are + verb-ing + object + keterangan waktu.",
  },
  {
    id: "q6c", difficulty: "A2", type: "dragDrop",
    prompt: "Susun menjadi kalimat rencana (be going to):",
    translation: "Kami akan mengunjungi Bali bulan depan.",
    tokens: ["going", "We", "visit", "month", "are", "to", "Bali", "next"],
    correct: ["We", "are", "going", "to", "visit", "Bali", "next", "month"],
    explanation: "Rencana: Subject + be + going to + verb bentuk dasar + object + keterangan waktu.",
  },
  {
    id: "q6d", difficulty: "A2", type: "dragDrop",
    prompt: "Susun menjadi kalimat tanya past simple:",
    translation: "Apakah kamu menonton film itu tadi malam?",
    tokens: ["you", "night", "the", "Did", "watch", "movie", "last"],
    correct: ["Did", "you", "watch", "the", "movie", "last", "night"],
    explanation: "Kalimat tanya past simple: Did + subject + verb bentuk dasar + object + keterangan waktu.",
  },
  {
    id: "q7b", difficulty: "A2", type: "missing",
    question: "Lengkapi kalimat dengan kata yang tepat:",
    template: "I usually ___ to work by bus, but yesterday I ___ a taxi.",
    blanks: ["go", "took"],
    options: ["go", "goes", "going", "took", "take", "taken"],
    explanation: "Present simple ('go') untuk kebiasaan — ditandai 'usually'. Past simple ('took') untuk kejadian kemarin — ditandai 'yesterday'.",
  },
  {
    id: "q7c", difficulty: "A2", type: "missing",
    question: "Lengkapi kalimat dengan kata yang tepat:",
    template: "There aren't ___ eggs in the fridge, so we need to buy ___.",
    blanks: ["any", "some"],
    options: ["any", "some", "much", "a", "an", "little"],
    explanation: "'Any' dipakai di kalimat negatif dan tanya, 'some' di kalimat positif. 'Much' dan 'little' hanya untuk benda tak terhitung, sedangkan 'eggs' terhitung.",
  },
  {
    id: "q7d", difficulty: "A2", type: "missing",
    question: "Lengkapi kalimat dengan bentuk perbandingan yang tepat:",
    template: "My brother is ___ than me, but I am the ___ in my class.",
    blanks: ["taller", "tallest"],
    options: ["tall", "taller", "tallest", "more tall", "most tall", "tallness"],
    explanation: "Kata sifat pendek: tambah '-er' + than untuk membandingkan dua hal (taller than), dan 'the' + '-est' untuk yang paling (the tallest).",
  },
  {
    id: "q8b", difficulty: "A2", type: "multiple",
    question: "'You ___ smoke here. It's a hospital.'",
    options: ["mustn't", "don't have to", "needn't", "might not"],
    correct: 0,
    explanation: "'Mustn't' = dilarang. 'Don't have to' dan 'needn't' artinya tidak wajib (boleh saja), bukan larangan.",
  },
  {
    id: "q8c", difficulty: "A2", type: "multiple",
    question: "'___ you swim when you were five?'",
    options: ["Can", "Could", "Should", "Must"],
    correct: 1,
    explanation: "'Could' adalah bentuk lampau dari 'can' — dipakai untuk kemampuan di masa lalu ('when you were five').",
  },
  {
    id: "q8d", difficulty: "A2", type: "multiple",
    question: "'How ___ sugar do you want in your tea?'",
    options: ["many", "much", "few", "long"],
    correct: 1,
    explanation: "'Sugar' benda tak terhitung, jadi memakai 'how much'. 'How many' untuk benda terhitung (how many eggs).",
  },
  {
    id: "q9b", difficulty: "A2", type: "fillChoice",
    question: "'I was born ___ 1998.'",
    context: "Pilih preposisi yang tepat.",
    options: ["in", "on", "at", "since"],
    correct: "in",
    explanation: "'In' untuk tahun, bulan, dan musim. 'On' untuk hari dan tanggal, 'at' untuk jam.",
  },
  {
    id: "q9c", difficulty: "A2", type: "fillChoice",
    question: "'She has worked here ___ 2019.'",
    context: "Pilih preposisi yang tepat.",
    options: ["for", "since", "ago", "during"],
    correct: "since",
    explanation: "'Since' + titik waktu mulai (since 2019). 'For' + lama waktu (for five years).",
  },
  {
    id: "q9d", difficulty: "A2", type: "fillChoice",
    question: "'The meeting is ___ Monday morning.'",
    context: "Pilih preposisi yang tepat.",
    options: ["in", "on", "at", "of"],
    correct: "on",
    explanation: "Nama hari selalu memakai 'on', termasuk 'on Monday morning'. Tanpa nama hari baru memakai 'in the morning'.",
  },
  {
    id: "l2b", difficulty: "A2", type: "multiple",
    audio: { lang: "en", text: "Hello, this is Doctor Brown's office. Your appointment is on Thursday at half past two, not on Tuesday. Please arrive ten minutes early and bring your insurance card." },
    question: "Dengarkan audio. Kapan janji temu dengan dokter?",
    options: [
      "Hari Selasa, jam 14.30",
      "Hari Kamis, jam 14.30",
      "Hari Kamis, jam 14.10",
      "Hari Selasa, jam 10.00",
    ],
    correct: 1,
    explanation: "Transkrip: 'Hello, this is Doctor Brown's office. Your appointment is on Thursday at half past two, not on Tuesday. Please arrive ten minutes early and bring your insurance card.' (Halo, ini kantor Dokter Brown. Janji temu Anda hari Kamis jam setengah tiga, bukan hari Selasa. Mohon datang sepuluh menit lebih awal dan bawa kartu asuransi Anda.) 'Thursday' = Kamis, 'Tuesday' = Selasa (disebut sebagai yang SALAH). 'Half past two' = 02.30. 'Ten minutes' = datang lebih awal, bukan jam janji.",
  },
  {
    id: "l2c", difficulty: "A2", type: "multiple",
    audio: { lang: "en", text: "Excuse me, how do I get to the library? Go straight on, then turn left at the bank. The library is next to the post office, opposite the park." },
    question: "Dengarkan audio. Di mana letak perpustakaannya?",
    options: [
      "Di sebelah bank, di seberang kantor pos",
      "Di sebelah kantor pos, di seberang taman",
      "Di dalam taman, dekat bank",
      "Di sebelah taman, di seberang bank",
    ],
    correct: 1,
    explanation: "Transkrip: 'Excuse me, how do I get to the library? Go straight on, then turn left at the bank. The library is next to the post office, opposite the park.' (Permisi, bagaimana cara ke perpustakaan? Lurus saja, lalu belok kiri di bank. Perpustakaannya di sebelah kantor pos, di seberang taman.) 'Next to' = di sebelah, 'opposite' = di seberang. Bank hanya patokan untuk belok, bukan letak perpustakaan.",
  },
  {
    id: "l2d", difficulty: "A2", type: "multiple",
    audio: { lang: "en", text: "Hi, I'd like a large coffee and two cheese sandwiches, please. That's eight pounds fifty. Here's ten pounds. And here's your change, one pound fifty." },
    question: "Dengarkan audio. Apa yang dipesan dan berapa harganya?",
    options: [
      "Satu kopi besar dan dua roti lapis keju — £8,50",
      "Dua kopi besar dan satu roti lapis keju — £10",
      "Satu kopi besar dan dua roti lapis keju — £1,50",
      "Dua kopi besar dan dua roti lapis keju — £8,50",
    ],
    correct: 0,
    explanation: "Transkrip: 'Hi, I'd like a large coffee and two cheese sandwiches, please. That's eight pounds fifty. Here's ten pounds. And here's your change, one pound fifty.' (Hai, saya pesan satu kopi besar dan dua roti lapis keju. Semuanya delapan pound lima puluh. Ini sepuluh pound. Dan ini kembaliannya, satu pound lima puluh.) Harga = £8,50. £10 adalah uang yang dibayarkan, £1,50 adalah kembalian ('change').",
  },

  // ═══════════════════════ B1 ═══════════════════════
  {
    id: "q10b", difficulty: "B1", type: "multiple",
    question: "Which sentence is correct?",
    options: [
      "I look forward to hear from you.",
      "I look forward to hearing from you.",
      "I look forward hearing from you.",
      "I am look forward to hear from you.",
    ],
    correct: 1,
    explanation: "Pada 'look forward to', kata 'to' adalah preposisi, jadi diikuti verb-ing (hearing), bukan verb bentuk dasar.",
  },
  {
    id: "q10c", difficulty: "B1", type: "multiple",
    question: "Which sentence uses 'used to' correctly?",
    options: [
      "I use to play football when I was a child.",
      "I used to playing football when I was a child.",
      "I used to play football when I was a child.",
      "I was used to play football when I was a child.",
    ],
    correct: 2,
    explanation: "'Used to + verb bentuk dasar' = kebiasaan di masa lalu yang sekarang sudah tidak dilakukan. Jangan tertukar dengan 'be used to + verb-ing' (terbiasa).",
  },
  {
    id: "q10d", difficulty: "B1", type: "multiple",
    question: "'By the time we arrived, the film ___.'",
    options: ["has already started", "had already started", "already starts", "was already start"],
    correct: 1,
    explanation: "Past perfect (had + past participle) untuk kejadian yang lebih dulu terjadi sebelum kejadian lampau lainnya: film mulai dulu, baru kami tiba.",
  },
  {
    id: "q11b", difficulty: "B1", type: "dragDrop",
    prompt: "Susun kalimat passive voice:",
    translation: "Jembatan ini dibangun pada tahun 1990.",
    tokens: ["built", "This", "1990", "was", "bridge", "in"],
    correct: ["This", "bridge", "was", "built", "in", "1990"],
    explanation: "Passive past: object + was/were + past participle + keterangan waktu.",
  },
  {
    id: "q11c", difficulty: "B1", type: "dragDrop",
    prompt: "Susun kalimat present perfect:",
    translation: "Saya belum pernah ke London.",
    tokens: ["never", "London", "I", "been", "have", "to"],
    correct: ["I", "have", "never", "been", "to", "London"],
    explanation: "Present perfect untuk pengalaman: Subject + have/has + never + past participle. 'Never' diletakkan di antara 'have' dan past participle.",
  },
  {
    id: "q11d", difficulty: "B1", type: "dragDrop",
    prompt: "Susun kalimat dengan relative clause:",
    translation: "Itu adalah pria yang membantu saya.",
    tokens: ["who", "That", "me", "the", "helped", "is", "man"],
    correct: ["That", "is", "the", "man", "who", "helped", "me"],
    explanation: "Relative clause: noun + who (untuk orang) + verb. 'Who helped me' menjelaskan pria yang mana.",
  },
  {
    id: "q12b", difficulty: "B1", type: "matching",
    prompt: "Jodohkan phrasal verb dengan artinya:",
    pairs: [
      { left: "turn down", right: "menolak" },
      { left: "find out", right: "mengetahui" },
      { left: "get along", right: "akur" },
      { left: "break down", right: "mogok" },
    ],
    explanation: "Phrasal verbs umum level B1: turn down an offer (menolak tawaran), find out the truth (mengetahui kebenaran), get along with someone (akur), the car broke down (mobilnya mogok).",
  },
  {
    id: "q12c", difficulty: "B1", type: "matching",
    prompt: "Jodohkan kata sifat dengan artinya:",
    pairs: [
      { left: "reliable", right: "dapat diandalkan" },
      { left: "stubborn", right: "keras kepala" },
      { left: "generous", right: "dermawan" },
      { left: "anxious", right: "cemas" },
    ],
    explanation: "Kata sifat untuk menggambarkan karakter dan perasaan — kosakata khas level B1 saat bercerita tentang orang lain.",
  },
  {
    id: "q12d", difficulty: "B1", type: "matching",
    prompt: "Jodohkan phrasal verb dengan artinya:",
    pairs: [
      { left: "carry on", right: "melanjutkan" },
      { left: "come across", right: "menemukan secara kebetulan" },
      { left: "set up", right: "mendirikan" },
      { left: "call off", right: "membatalkan" },
    ],
    explanation: "Phrasal verbs umum level B1: carry on working (lanjut bekerja), come across an old photo (tak sengaja menemukan foto lama), set up a company (mendirikan perusahaan), call off a meeting (membatalkan rapat).",
  },
  {
    id: "q13b", difficulty: "B1", type: "missing",
    question: "Lengkapi kalimat pengandaian dengan kata yang tepat:",
    template: "I wish I ___ more free time, so I ___ learn to play the guitar.",
    blanks: ["had", "could"],
    options: ["had", "have", "having", "could", "can", "will"],
    explanation: "'I wish' + past simple untuk keinginan yang tidak sesuai kenyataan sekarang (wish I had). Akibatnya juga memakai bentuk lampau: could, bukan can.",
  },
  {
    id: "q13c", difficulty: "B1", type: "missing",
    question: "Lengkapi kalimat dengan kata yang tepat:",
    template: "She has been working here ___ 2015, so she has worked here ___ almost ten years.",
    blanks: ["since", "for"],
    options: ["since", "for", "from", "during", "ago", "while"],
    explanation: "'Since' + titik waktu mulai (since 2015), 'for' + lama waktu (for almost ten years). Keduanya umum dipakai dengan present perfect.",
  },
  {
    id: "q13d", difficulty: "B1", type: "missing",
    question: "Lengkapi kalimat dengan bentuk kata kerja yang tepat:",
    template: "Although he was tired, he kept ___ because he wanted ___ the report.",
    blanks: ["working", "to finish"],
    options: ["working", "to work", "work", "to finish", "finishing", "finish"],
    explanation: "'Keep' diikuti verb-ing (kept working), sedangkan 'want' diikuti to + verb (wanted to finish). Pola gerund vs infinitive ini ciri khas level B1.",
  },
  {
    id: "q14b", difficulty: "B1", type: "fillChoice",
    question: "Reported: He said, 'I will call you.' = He said he ___ call me.",
    context: "Shift tense untuk reported speech.",
    options: ["will", "would", "can", "did"],
    correct: "would",
    explanation: "Dalam reported speech, 'will' mundur menjadi 'would'.",
  },
  {
    id: "q14c", difficulty: "B1", type: "fillChoice",
    question: "'The man ___ car was stolen went to the police.'",
    context: "Pilih kata penghubung relative clause yang tepat.",
    options: ["who", "whose", "which", "whom"],
    correct: "whose",
    explanation: "'Whose' menyatakan kepemilikan: the man whose car = pria yang mobilnya. 'Who' untuk subjek orang, 'which' untuk benda.",
  },
  {
    id: "q14d", difficulty: "B1", type: "fillChoice",
    question: "'I'm not used to ___ up so early.'",
    context: "Pilih bentuk kata kerja yang tepat.",
    options: ["get", "getting", "got", "gets"],
    correct: "getting",
    explanation: "'Be used to' (terbiasa) diikuti verb-ing. Beda dengan 'used to + verb' (dulu biasa melakukan).",
  },
  {
    id: "l3b", difficulty: "B1", type: "multiple",
    audio: { lang: "en", text: "I was going to call you last night, but my phone ran out of battery before I got home." },
    question: "Dengarkan audio. Pilih terjemahan yang paling tepat:",
    options: [
      "Saya meneleponmu tadi malam, lalu baterai HP saya habis setelah saya sampai di rumah.",
      "Saya tadinya mau meneleponmu tadi malam, tapi baterai HP saya habis sebelum saya sampai di rumah.",
      "Saya akan meneleponmu malam ini kalau baterai HP saya tidak habis sebelum sampai di rumah.",
      "Saya tidak mau meneleponmu tadi malam karena HP saya tertinggal di rumah.",
    ],
    correct: 1,
    explanation: "Transkrip: 'I was going to call you last night, but my phone ran out of battery before I got home.' Pola 'was going to + verb' = rencana di masa lalu yang TIDAK jadi dilakukan (tadinya mau). 'Ran out of battery' = kehabisan baterai. 'Before I got home' = sebelum sampai rumah, bukan setelahnya.",
  },
  {
    id: "l3c", difficulty: "B1", type: "multiple",
    audio: { lang: "en", text: "Unless it stops raining in the next hour, they'll have to cancel the outdoor concert." },
    question: "Dengarkan audio. Pilih terjemahan yang paling tepat:",
    options: [
      "Karena hujan sudah berhenti satu jam yang lalu, konser luar ruangan itu tidak jadi dibatalkan.",
      "Kalau hujan berhenti dalam satu jam ke depan, mereka akan membatalkan konser luar ruangan itu.",
      "Kalau hujan tidak berhenti dalam satu jam ke depan, mereka terpaksa membatalkan konser luar ruangan itu.",
      "Mereka sudah membatalkan konser luar ruangan itu karena hujan turun selama satu jam.",
    ],
    correct: 2,
    explanation: "Transkrip: 'Unless it stops raining in the next hour, they'll have to cancel the outdoor concert.' 'Unless' = 'if ... not' (kalau tidak). Jadi 'unless it stops raining' = kalau hujan TIDAK berhenti. 'They'll have to' = mereka terpaksa/harus (belum terjadi), bukan 'sudah membatalkan'.",
  },
  {
    id: "l3d", difficulty: "B1", type: "multiple",
    audio: { lang: "en", text: "She told me she had already finished the report, so I didn't need to help her after all." },
    question: "Dengarkan audio. Pilih terjemahan yang paling tepat:",
    options: [
      "Dia bilang dia sudah menyelesaikan laporannya, jadi ternyata saya tidak perlu membantunya.",
      "Dia meminta saya membantu menyelesaikan laporannya karena belum selesai.",
      "Dia bilang akan menyelesaikan laporannya setelah saya membantunya.",
      "Saya sudah membantunya menyelesaikan laporan, jadi dia tidak perlu mengerjakannya lagi.",
    ],
    correct: 0,
    explanation: "Transkrip: 'She told me she had already finished the report, so I didn't need to help her after all.' 'Had already finished' (past perfect) = sudah selesai sebelum dia memberi tahu. 'Didn't need to' = tidak perlu. 'After all' = ternyata (berlawanan dengan dugaan awal).",
  },
  {
    id: "l4b", difficulty: "B1", type: "missing",
    audio: { lang: "en", text: "Before you accept the job offer, you should compare the salary and check how far the office is from your home." },
    question: "Dengarkan audio, lalu isi dua kata yang hilang:",
    template: "Before you ___ the job offer, you should compare the salary and check how ___ the office is from your home.",
    blanks: ["accept", "far"],
    options: ["accept", "except", "expect", "far", "fur", "four"],
    explanation: "Transkrip: 'Before you accept the job offer, you should compare the salary and check how far the office is from your home.' (Sebelum kamu menerima tawaran kerja itu, sebaiknya bandingkan gajinya dan cek seberapa jauh kantornya dari rumahmu.) 'Accept' /əkˈsept/ = menerima; 'except' = kecuali dan 'expect' = mengharapkan bunyinya mirip tapi maknanya tidak cocok. 'How far' = seberapa jauh; 'fur' = bulu, 'four' = empat.",
  },
  {
    id: "l4c", difficulty: "B1", type: "missing",
    audio: { lang: "en", text: "I'd rather walk to work than take the bus, because the traffic is terrible and the weather is lovely today." },
    question: "Dengarkan audio, lalu isi dua kata yang hilang:",
    template: "I'd rather ___ to work than take the bus, because the traffic is terrible and the ___ is lovely today.",
    blanks: ["walk", "weather"],
    options: ["walk", "work", "woke", "weather", "whether", "wetter"],
    explanation: "Transkrip: 'I'd rather walk to work than take the bus, because the traffic is terrible and the weather is lovely today.' (Saya lebih suka jalan kaki ke kantor daripada naik bus, karena macetnya parah dan cuacanya bagus hari ini.) 'Walk' /wɔːk/ = berjalan, jangan tertukar dengan 'work' /wɜːk/ = bekerja. 'Weather' = cuaca; 'whether' = apakah — bunyinya sama, tapi hanya 'weather' yang bisa 'lovely'.",
  },
  {
    id: "l4d", difficulty: "B1", type: "missing",
    audio: { lang: "en", text: "Could you remind me to send the invoice tomorrow? I always forget things when I'm in a hurry." },
    question: "Dengarkan audio, lalu isi dua kata yang hilang:",
    template: "Could you ___ me to send the invoice tomorrow? I always ___ things when I'm in a hurry.",
    blanks: ["remind", "forget"],
    options: ["remind", "remain", "rewind", "forget", "forgive", "forgot"],
    explanation: "Transkrip: 'Could you remind me to send the invoice tomorrow? I always forget things when I'm in a hurry.' (Bisakah kamu mengingatkan saya untuk mengirim invoice besok? Saya selalu lupa kalau sedang terburu-buru.) 'Remind' = mengingatkan; 'remain' = tetap, 'rewind' = memutar ulang. Setelah 'always' untuk kebiasaan dipakai present simple 'forget', bukan 'forgot'; 'forgive' = memaafkan.",
  },

  // ═══════════════════════ B2 ═══════════════════════
  {
    id: "q15b", difficulty: "B2", type: "multiple",
    question: "Which sentence uses a mixed conditional correctly?",
    options: [
      "If I had studied medicine, I would be a doctor now.",
      "If I studied medicine, I would have been a doctor now.",
      "If I would study medicine, I am a doctor now.",
      "If I have studied medicine, I would be a doctor now.",
    ],
    correct: 0,
    explanation: "Mixed conditional: If + past perfect (syarat di masa lalu), would + verb (akibat di masa sekarang). Dulu tidak kuliah kedokteran → sekarang bukan dokter.",
  },
  {
    id: "q15c", difficulty: "B2", type: "multiple",
    question: "'I'd rather you ___ anyone about this.'",
    options: ["don't tell", "didn't tell", "won't tell", "not to tell"],
    correct: 1,
    explanation: "'Would rather + subject lain' diikuti past simple walaupun maknanya sekarang/masa depan: I'd rather you didn't tell anyone.",
  },
  {
    id: "q15d", difficulty: "B2", type: "multiple",
    question: "Which sentence is correct?",
    options: [
      "She suggested me to take a break.",
      "She suggested that I take a break.",
      "She suggested me taking a break.",
      "She suggested to take me a break.",
    ],
    correct: 1,
    explanation: "'Suggest' tidak bisa diikuti object + to-infinitive. Polanya: suggest + that + subject + verb bentuk dasar, atau suggest + verb-ing.",
  },
  {
    id: "q16b", difficulty: "B2", type: "dragDrop",
    prompt: "Susun kalimat dengan inversi formal (untuk penekanan):",
    translation: "Baru saja saya tiba, hujan pun turun.",
    tokens: ["had", "rained", "Hardly", "when", "arrived", "I", "it"],
    correct: ["Hardly", "had", "I", "arrived", "when", "it", "rained"],
    explanation: "Setelah 'hardly' di awal kalimat, auxiliary dan subject dibalik (had I arrived), lalu disambung 'when'.",
  },
  {
    id: "q16c", difficulty: "B2", type: "dragDrop",
    prompt: "Susun kalimat dengan inversi formal (untuk penekanan):",
    translation: "Sedikit pun kami tidak tahu tentang rencana itu.",
    tokens: ["did", "plan", "Little", "know", "the", "we", "about"],
    correct: ["Little", "did", "we", "know", "about", "the", "plan"],
    explanation: "Setelah adverb negatif 'little' di awal kalimat, pakai inversi: did + subject + verb bentuk dasar.",
  },
  {
    id: "q16d", difficulty: "B2", type: "dragDrop",
    prompt: "Susun kalimat pengandaian dengan inversi (tanpa 'if'):",
    translation: "Seandainya dia meminta, kami pasti sudah membantunya.",
    tokens: ["she", "helped", "Had", "would", "asked", "her", "we", "have"],
    correct: ["Had", "she", "asked", "we", "would", "have", "helped", "her"],
    explanation: "Third conditional formal tanpa 'if': Had + subject + past participle, subject + would have + past participle. Sama dengan 'If she had asked, …'.",
  },
  {
    id: "q17b", difficulty: "B2", type: "missing",
    question: "Lengkapi kalimat dengan kata yang tepat:",
    template: "Rising sea levels pose a serious ___ to coastal cities, so governments must take ___ measures.",
    blanks: ["threat", "preventive"],
    options: ["threat", "treat", "thread", "preventive", "prevented", "preventing"],
    explanation: "Kolokasi 'pose a threat to' = menjadi ancaman bagi ('treat' = traktiran/memperlakukan, 'thread' = benang). 'Preventive measures' = langkah pencegahan — bentuk kata sifatnya 'preventive'.",
  },
  {
    id: "q17c", difficulty: "B2", type: "missing",
    question: "Lengkapi kalimat dengan kata yang tepat:",
    template: "Her argument was so ___ that nobody could ___ it.",
    blanks: ["convincing", "refute"],
    options: ["convincing", "convinced", "convince", "refute", "refuse", "reduce"],
    explanation: "'Convincing' (meyakinkan) menggambarkan argumennya; 'convinced' menggambarkan orang yang merasa yakin. 'Refute an argument' = membantah argumen — 'refuse' berarti menolak tawaran/permintaan.",
  },
  {
    id: "q17d", difficulty: "B2", type: "missing",
    question: "Lengkapi kalimat dengan kata yang tepat:",
    template: "The government has ___ a new law that is expected to ___ unemployment significantly.",
    blanks: ["introduced", "reduce"],
    options: ["introduced", "interfered", "reduce", "rise", "arisen", "decline"],
    explanation: "Kolokasi 'introduce a law' = memberlakukan undang-undang. 'Reduce' butuh objek (reduce unemployment); 'rise' dan 'decline' tidak bisa langsung diikuti objek seperti itu.",
  },
  {
    id: "q18b", difficulty: "B2", type: "multiple",
    question: "Which sentence is the most formal?",
    options: [
      "We need to look into the problem.",
      "We need to investigate the problem.",
      "We gotta check out the problem.",
      "We need to have a look at the problem.",
    ],
    correct: 1,
    explanation: "Tulisan formal/akademis memilih kata kerja tunggal asal Latin ('investigate') ketimbang phrasal verb ('look into') atau bentuk percakapan ('gotta', 'have a look').",
  },
  {
    id: "q18c", difficulty: "B2", type: "multiple",
    question: "Which sentence uses a participle clause correctly?",
    options: [
      "Having finished the report, she went home.",
      "Having finished the report, the office was closed.",
      "Finished the report, she going home.",
      "She having finished the report, went home she.",
    ],
    correct: 0,
    explanation: "Subjek participle clause harus sama dengan subjek kalimat utama: yang menyelesaikan laporan adalah 'she'. Pada 'the office was closed', seolah-olah kantornya yang menyelesaikan laporan (dangling participle).",
  },
  {
    id: "q18d", difficulty: "B2", type: "multiple",
    question: "'The proposal was rejected ___ its high cost.'",
    options: ["because", "on account of", "despite of", "although"],
    correct: 1,
    explanation: "'On account of' + noun phrase = karena (formal). 'Because' dan 'although' harus diikuti klausa (subject + verb), dan 'despite' tidak pernah diikuti 'of'.",
  },
  {
    id: "l5b", difficulty: "B2", type: "multiple",
    audio: { lang: "en", text: "Thank you for calling Greenfield Bank. We are currently experiencing a high volume of calls, and the waiting time is about twenty minutes. Alternatively, most requests can be completed in under five minutes using our mobile app." },
    question: "Dengarkan pesan ini. Kesimpulan yang PALING masuk akal adalah:",
    options: [
      "Bank sedang tutup, jadi nasabah harus menelepon lagi dua puluh menit kemudian.",
      "Nasabah disarankan memakai aplikasi karena lebih cepat daripada menunggu di telepon.",
      "Aplikasi bank sedang bermasalah sehingga banyak nasabah menelepon.",
      "Semua permintaan hanya bisa diselesaikan lewat telepon dalam waktu lima menit.",
    ],
    correct: 1,
    explanation: "Transkrip: 'Thank you for calling Greenfield Bank. We are currently experiencing a high volume of calls, and the waiting time is about twenty minutes. Alternatively, most requests can be completed in under five minutes using our mobile app.' (Terima kasih telah menghubungi Greenfield Bank. Saat ini panggilan sedang sangat banyak, dan waktu tunggunya sekitar dua puluh menit. Sebagai alternatif, sebagian besar permintaan bisa diselesaikan dalam waktu kurang dari lima menit lewat aplikasi kami.) Kuncinya 'Alternatively': bank menawarkan jalan lain yang lebih cepat (5 menit vs 20 menit). Bank tidak tutup, dan tidak ada yang menyebut aplikasi bermasalah.",
  },
  {
    id: "l5c", difficulty: "B2", type: "multiple",
    audio: { lang: "en", text: "The new library was supposed to open in March. However, because of delays in the delivery of materials, the opening has been pushed back to the autumn, and the budget has had to be increased as a result." },
    question: "Dengarkan berita ini. Kesimpulan yang PALING masuk akal adalah:",
    options: [
      "Perpustakaan baru sudah dibuka pada bulan Maret sesuai rencana.",
      "Pembukaan perpustakaan dimajukan karena bahan bangunan datang lebih cepat.",
      "Proyek perpustakaan dibatalkan karena anggarannya habis.",
      "Proyek perpustakaan itu terlambat dan menjadi lebih mahal dari rencana semula.",
    ],
    correct: 3,
    explanation: "Transkrip: 'The new library was supposed to open in March. However, because of delays in the delivery of materials, the opening has been pushed back to the autumn, and the budget has had to be increased as a result.' (Perpustakaan baru seharusnya dibuka pada bulan Maret. Namun, karena pengiriman bahan terlambat, pembukaannya diundur ke musim gugur, dan akibatnya anggarannya harus ditambah.) 'Was supposed to' = seharusnya (tapi tidak terjadi). 'Pushed back' = diundur, bukan dimajukan. 'Budget … increased' = biayanya bertambah, bukan habis atau dibatalkan.",
  },
  {
    id: "l5d", difficulty: "B2", type: "multiple",
    audio: { lang: "en", text: "Although sales fell slightly in the first quarter, the manager said she was not worried, since the company usually sells far more during the holiday season at the end of the year." },
    question: "Dengarkan laporan ini. Kesimpulan yang PALING masuk akal adalah:",
    options: [
      "Manajer khawatir karena penjualan terus menurun sepanjang tahun.",
      "Penjualan naik tajam pada kuartal pertama berkat musim liburan.",
      "Manajer memperkirakan penjualan akan membaik pada akhir tahun, jadi penurunan itu tidak dianggap masalah besar.",
      "Perusahaan berencana berhenti berjualan sampai musim liburan tiba.",
    ],
    correct: 2,
    explanation: "Transkrip: 'Although sales fell slightly in the first quarter, the manager said she was not worried, since the company usually sells far more during the holiday season at the end of the year.' (Walaupun penjualan sedikit turun pada kuartal pertama, manajer berkata dia tidak khawatir, karena perusahaan biasanya menjual jauh lebih banyak selama musim liburan di akhir tahun.) 'Although … not worried' menunjukkan penurunan itu tidak dianggap serius, dan 'since' memberi alasannya: penjualan biasanya naik di akhir tahun. Penurunannya hanya 'slightly' dan hanya di kuartal pertama.",
  },
];
